// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

// A node in the orchard graph. Every node has a globally-unique id so
// clients can fetch it via Query.node(id) regardless of which concrete
// type it is.
type Node interface {
	IsNode()
	// Globally-unique id (e.g. "Host:<machineId>").
	GetID() string
}

type ClaudeInstance struct {
	// Stable id; ws-b-claudeinstance formalises (host_id, claudePid).
	ID string `json:"id"`
}

type Health struct {
	// Daemon health status — 'ok' when serving.
	Status string `json:"status"`
	// Uptime in seconds since daemon started.
	UptimeS int64 `json:"uptimeS"`
}

// A machine that orchard reflects. Identity is the OS-issued machine id
// (/etc/machine-id on Linux, IOPlatformUUID on macOS). Resource load
// samples on a 5s TTL.
type Host struct {
	// Stable orchard id — "Host:<machineId>".
	ID string `json:"id"`
	// OS-issued machine id. Linux: /etc/machine-id. macOS: IOPlatformUUID.
	MachineID string `json:"machineId"`
	// Hostname as reported by the OS at boot.
	Hostname string `json:"hostname"`
	// Operating system family — 'darwin', 'linux', etc.
	Os string `json:"os"`
	// Kernel version string (e.g. 'Darwin 25.4.0', 'Linux 6.5.0'). Nullable when unavailable.
	Kernel *string `json:"kernel,omitempty"`
	// Reachable network address. v1: null for the local host; Workstream F populates for peers.
	Address *string `json:"address,omitempty"`
	// True when the daemon last heard from this host. v1: always true for local host.
	Reachable bool `json:"reachable"`
	// Live CPU, memory, disk, and load averages. Polled every 5s; null briefly at cold boot before the first sample lands.
	ResourceLoad *ResourceLoad `json:"resourceLoad,omitempty"`
	// RFC 3339 timestamp of the last successful read. v1: time of the last load sample for the local host.
	LastSeenAt string `json:"lastSeenAt"`
	// Peer hosts this daemon federates with. v1: always empty; Workstream F populates.
	Peers []*Host `json:"peers"`
	// Processes visible to this host's `ps` adapter, optionally filtered.
	Processes []*Process `json:"processes"`
}

func (Host) IsNode() {}

// Globally-unique id (e.g. "Host:<machineId>").
func (this Host) GetID() string { return this.ID }

type Process struct {
	// Stable id formatted as `<host>:<pid>`.
	ID string `json:"id"`
	// Host this process is running on.
	Host *Host `json:"host"`
	// Process id.
	Pid int64 `json:"pid"`
	// Parent process id (0 for kernel/launchd-rooted processes).
	Ppid int64 `json:"ppid"`
	// Command basename (e.g. 'sleep', 'claude'). Cheap, always populated.
	Command string `json:"command"`
	// Full argv. Slow path — opt-in (separate `ps -wwax -o pid,args` lookup).
	Args []string `json:"args,omitempty"`
	// Current working directory. Slow path — opt-in (lsof on macOS, /proc on Linux).
	Cwd *string `json:"cwd,omitempty"`
	// Process start time (RFC3339 if parseable, otherwise the raw `lstart` field).
	StartedAt string `json:"startedAt"`
	// CPU percent as reported by ps.
	CPUPercent float64 `json:"cpuPercent"`
	// Resident memory in bytes (RSS * 1024 from ps).
	MemBytes int64 `json:"memBytes"`
	// Controlling terminal, or null if none.
	Tty *string `json:"tty,omitempty"`
	// Worktree this process is running inside, derived from cwd. Null until ws-b-git wires the lookup.
	Worktree *Worktree `json:"worktree,omitempty"`
	// Claude instance back-edge — populated when this pid is the foreground claude pid. Null until ws-b-claudeinstance lands.
	ClaudeInstance *ClaudeInstance `json:"claudeInstance,omitempty"`
}

func (Process) IsNode() {}

// Globally-unique id (e.g. "Host:<machineId>").
func (this Process) GetID() string { return this.ID }

type ProcessFilter struct {
	// Match processes whose command basename is in this list.
	CommandIn []string `json:"commandIn,omitempty"`
	// Match processes whose cwd starts with this prefix. Forces cwd resolution.
	CwdPrefix *string `json:"cwdPrefix,omitempty"`
	// Match processes by pid.
	PidIn []int64 `json:"pidIn,omitempty"`
}

// A project (git repo) registered in the orchard config. The config file is the source of truth; the daemon reflects it via fsnotify.
type Project struct {
	// Stable identifier — slug of `name`, falling back to a short hash of `directory`. Survives re-registration.
	ID string `json:"id"`
	// Absolute filesystem path to the project's working tree.
	Directory string `json:"directory"`
	// Human-readable label. Defaults to the basename of `directory` when not specified in the config.
	Name string `json:"name"`
	// Worktrees discovered for this project — the project's main checkout plus everything under `.git/worktrees/`.
	Worktrees []*Worktree `json:"worktrees"`
}

func (Project) IsNode() {}

// Globally-unique id (e.g. "Host:<machineId>").
func (this Project) GetID() string { return this.ID }

type Query struct {
}

// A snapshot of a host's resource utilisation. Percentages are 0..100.
// Load averages are the kernel-reported 1/5/15-minute moving averages.
type ResourceLoad struct {
	// Aggregate CPU usage 0..100.
	CPUPercent float64 `json:"cpuPercent"`
	// Used memory as a percentage of total physical memory, 0..100.
	MemPercent float64 `json:"memPercent"`
	// Used disk on the root filesystem as a percentage, 0..100.
	DiskPercent float64 `json:"diskPercent"`
	// 1-minute load average.
	LoadAvg1m float64 `json:"loadAvg1m"`
	// 5-minute load average.
	LoadAvg5m float64 `json:"loadAvg5m"`
	// 15-minute load average.
	LoadAvg15m float64 `json:"loadAvg15m"`
}

// A git worktree — either the project's main checkout or one created with `git worktree add`. See ADR-011 §5.1.
type Worktree struct {
	// Stable identifier formatted as `<project_id>:<worktree_name>`. The main checkout uses the worktree name `main`.
	ID string `json:"id"`
	// Absolute filesystem path to the worktree.
	Path string `json:"path"`
	// Branch the worktree currently has checked out. Empty string for detached HEAD or bare worktrees.
	Branch string `json:"branch"`
	// Resolved 40-character SHA the worktree's HEAD points at. Empty string when HEAD cannot be resolved (e.g. an unborn branch).
	Head string `json:"head"`
	// True when HEAD references a deleted branch or otherwise fails to resolve to a commit. Bare worktrees still appear in the list — they just have no live branch.
	Bare bool `json:"bare"`
	// Processes whose cwd lies under `path`. Resolved by the ps provider (ws-b-ps); returns `[]` until that provider lands.
	Processes []*Process `json:"processes"`
}

func (Worktree) IsNode() {}

// Globally-unique id (e.g. "Host:<machineId>").
func (this Worktree) GetID() string { return this.ID }
