// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Node interface {
	IsNode()
	// Stable, host-qualified identifier (e.g. `<host>:<pid>` for a Process).
	GetID() string
}

type ClaudeInstance struct {
	// Stable id; ws-b-claudeinstance formalises (host_id, claudePid).
	ID string `json:"id"`
}

type Health struct {
	// Daemon health status — 'ok' when serving.
	Status string `json:"status"`
	// Uptime in seconds since daemon started.
	UptimeS int64 `json:"uptimeS"`
}

type Host struct {
	// Host identifier. v1 is a stable string; ws-g formalises (machineId, hostname, …).
	ID string `json:"id"`
	// Processes visible to this host's `ps` adapter, optionally filtered.
	Processes []*Process `json:"processes"`
}

type Process struct {
	// Stable id formatted as `<host>:<pid>`.
	ID string `json:"id"`
	// Host this process is running on.
	Host *Host `json:"host"`
	// Process id.
	Pid int64 `json:"pid"`
	// Parent process id (0 for kernel/launchd-rooted processes).
	Ppid int64 `json:"ppid"`
	// Command basename (e.g. 'sleep', 'claude'). Cheap, always populated.
	Command string `json:"command"`
	// Full argv. Slow path — opt-in (separate `ps -wwax -o pid,args` lookup).
	Args []string `json:"args,omitempty"`
	// Current working directory. Slow path — opt-in (lsof on macOS, /proc on Linux).
	Cwd *string `json:"cwd,omitempty"`
	// Process start time (RFC3339 if parseable, otherwise the raw `lstart` field).
	StartedAt string `json:"startedAt"`
	// CPU percent as reported by ps.
	CPUPercent float64 `json:"cpuPercent"`
	// Resident memory in bytes (RSS * 1024 from ps).
	MemBytes int64 `json:"memBytes"`
	// Controlling terminal, or null if none.
	Tty *string `json:"tty,omitempty"`
	// Worktree this process is running inside, derived from cwd. Null until ws-b-git lands.
	Worktree *Worktree `json:"worktree,omitempty"`
	// Claude instance back-edge — populated when this pid is the foreground claude pid. Null until ws-b-claudeinstance lands.
	ClaudeInstance *ClaudeInstance `json:"claudeInstance,omitempty"`
}

func (Process) IsNode() {}

// Stable, host-qualified identifier (e.g. `<host>:<pid>` for a Process).
func (this Process) GetID() string { return this.ID }

type ProcessFilter struct {
	// Match processes whose command basename is in this list.
	CommandIn []string `json:"commandIn,omitempty"`
	// Match processes whose cwd starts with this prefix. Forces cwd resolution.
	CwdPrefix *string `json:"cwdPrefix,omitempty"`
	// Match processes by pid.
	PidIn []int64 `json:"pidIn,omitempty"`
}

type Query struct {
}

type Worktree struct {
	// Stable id; ws-b-git formalises (host_id, path).
	ID string `json:"id"`
}
