package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	graphql1 "github.com/drewdrewthis/git-orchard-rs/daemon/graphql"
)

// Worktree is the resolver for the worktree field.
func (r *claudeInstanceResolver) Worktree(ctx context.Context, obj *graphql1.ClaudeInstance) (*graphql1.Worktree, error) {
	panic(fmt.Errorf("not implemented: Worktree - worktree"))
}

// Conversation is the resolver for the conversation field.
func (r *claudeInstanceResolver) Conversation(ctx context.Context, obj *graphql1.ClaudeInstance) (*graphql1.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversation - conversation"))
}

// Peers is the resolver for the peers field.
func (r *hostResolver) Peers(ctx context.Context, obj *graphql1.Host) ([]*graphql1.Host, error) {
	panic(fmt.Errorf("not implemented: Peers - peers"))
}

// Version is the resolver for the version field.
func (r *hostResolver) Version(ctx context.Context, obj *graphql1.Host) (*string, error) {
	panic(fmt.Errorf("not implemented: Version - version"))
}

// Processes is the resolver for the processes field.
func (r *hostResolver) Processes(ctx context.Context, obj *graphql1.Host, filter *graphql1.ProcessFilter) ([]*graphql1.Process, error) {
	panic(fmt.Errorf("not implemented: Processes - processes"))
}

// Labels is the resolver for the labels field.
func (r *issueResolver) Labels(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Label, error) {
	panic(fmt.Errorf("not implemented: Labels - labels"))
}

// BlockedByIssues is the resolver for the blockedByIssues field.
func (r *issueResolver) BlockedByIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: BlockedByIssues - blockedByIssues"))
}

// BlockingIssues is the resolver for the blockingIssues field.
func (r *issueResolver) BlockingIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: BlockingIssues - blockingIssues"))
}

// SubIssues is the resolver for the subIssues field.
func (r *issueResolver) SubIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: SubIssues - subIssues"))
}

// ParentIssue is the resolver for the parentIssue field.
func (r *issueResolver) ParentIssue(ctx context.Context, obj *graphql1.Issue) (*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: ParentIssue - parentIssue"))
}

// DaemonReload is the resolver for the daemonReload field.
func (r *mutationResolver) DaemonReload(ctx context.Context) (*graphql1.DaemonState, error) {
	panic(fmt.Errorf("not implemented: DaemonReload - daemonReload"))
}

// SendTextToPane is the resolver for the sendTextToPane field.
func (r *mutationResolver) SendTextToPane(ctx context.Context, paneID string, text string) (bool, error) {
	panic(fmt.Errorf("not implemented: SendTextToPane - sendTextToPane"))
}

// Host is the resolver for the host field.
func (r *processResolver) Host(ctx context.Context, obj *graphql1.Process) (*graphql1.Host, error) {
	panic(fmt.Errorf("not implemented: Host - host"))
}

// Args is the resolver for the args field.
func (r *processResolver) Args(ctx context.Context, obj *graphql1.Process) ([]string, error) {
	panic(fmt.Errorf("not implemented: Args - args"))
}

// Cwd is the resolver for the cwd field.
func (r *processResolver) Cwd(ctx context.Context, obj *graphql1.Process) (*string, error) {
	panic(fmt.Errorf("not implemented: Cwd - cwd"))
}

// Worktree is the resolver for the worktree field.
func (r *processResolver) Worktree(ctx context.Context, obj *graphql1.Process) (*graphql1.Worktree, error) {
	panic(fmt.Errorf("not implemented: Worktree - worktree"))
}

// ClaudeInstance is the resolver for the claudeInstance field.
func (r *processResolver) ClaudeInstance(ctx context.Context, obj *graphql1.Process) (*graphql1.ClaudeInstance, error) {
	panic(fmt.Errorf("not implemented: ClaudeInstance - claudeInstance"))
}

// Mergeable is the resolver for the mergeable field.
func (r *pullRequestResolver) Mergeable(ctx context.Context, obj *graphql1.PullRequest) (graphql1.MergeableState, error) {
	panic(fmt.Errorf("not implemented: Mergeable - mergeable"))
}

// MergeStateStatus is the resolver for the mergeStateStatus field.
func (r *pullRequestResolver) MergeStateStatus(ctx context.Context, obj *graphql1.PullRequest) (string, error) {
	panic(fmt.Errorf("not implemented: MergeStateStatus - mergeStateStatus"))
}

// ReviewDecision is the resolver for the reviewDecision field.
func (r *pullRequestResolver) ReviewDecision(ctx context.Context, obj *graphql1.PullRequest) (*graphql1.ReviewDecisionEnum, error) {
	panic(fmt.Errorf("not implemented: ReviewDecision - reviewDecision"))
}

// StatusCheckRollup is the resolver for the statusCheckRollup field.
func (r *pullRequestResolver) StatusCheckRollup(ctx context.Context, obj *graphql1.PullRequest) (graphql1.CiStatus, error) {
	panic(fmt.Errorf("not implemented: StatusCheckRollup - statusCheckRollup"))
}

// Labels is the resolver for the labels field.
func (r *pullRequestResolver) Labels(ctx context.Context, obj *graphql1.PullRequest) ([]*graphql1.Label, error) {
	panic(fmt.Errorf("not implemented: Labels - labels"))
}

// ClaudeAccounts is the resolver for the claudeAccounts field.
func (r *queryResolver) ClaudeAccounts(ctx context.Context) ([]*graphql1.ClaudeAccount, error) {
	panic(fmt.Errorf("not implemented: ClaudeAccounts - claudeAccounts"))
}

// ClaudeCli is the resolver for the claudeCli field.
func (r *queryResolver) ClaudeCli(ctx context.Context, tool graphql1.ClaudeCliTool, args []string) (any, error) {
	panic(fmt.Errorf("not implemented: ClaudeCli - claudeCli"))
}

// ClaudeInstances is the resolver for the claudeInstances field.
func (r *queryResolver) ClaudeInstances(ctx context.Context) ([]*graphql1.ClaudeInstance, error) {
	panic(fmt.Errorf("not implemented: ClaudeInstances - claudeInstances"))
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*graphql1.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversations - conversations"))
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*graphql1.Conversation, error) {
	panic(fmt.Errorf("not implemented: Conversation - conversation"))
}

// Contract is the resolver for the contract field.
func (r *queryResolver) Contract(ctx context.Context, id string) (*graphql1.Contract, error) {
	panic(fmt.Errorf("not implemented: Contract - contract"))
}

// Contracts is the resolver for the contracts field.
func (r *queryResolver) Contracts(ctx context.Context, filter *graphql1.ContractFilter) ([]*graphql1.Contract, error) {
	panic(fmt.Errorf("not implemented: Contracts - contracts"))
}

// DaemonState is the resolver for the daemonState field.
func (r *queryResolver) DaemonState(ctx context.Context) (*graphql1.DaemonState, error) {
	panic(fmt.Errorf("not implemented: DaemonState - daemonState"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*graphql1.Health, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Version - version"))
}

// SchemaSdl is the resolver for the schemaSDL field.
func (r *queryResolver) SchemaSdl(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: SchemaSdl - schemaSDL"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (graphql1.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Gh is the resolver for the gh field.
func (r *queryResolver) Gh(ctx context.Context, query string, variables any) (any, error) {
	panic(fmt.Errorf("not implemented: Gh - gh"))
}

// PullRequests is the resolver for the pullRequests field.
func (r *queryResolver) PullRequests(ctx context.Context, repo string, state *graphql1.PullRequestState) ([]*graphql1.PullRequest, error) {
	panic(fmt.Errorf("not implemented: PullRequests - pullRequests"))
}

// OpenPullRequests is the resolver for the openPullRequests field.
func (r *queryResolver) OpenPullRequests(ctx context.Context, repo string, author *string) ([]*graphql1.PullRequest, error) {
	panic(fmt.Errorf("not implemented: OpenPullRequests - openPullRequests"))
}

// Issues is the resolver for the issues field.
func (r *queryResolver) Issues(ctx context.Context, repo string, state *graphql1.IssueState) ([]*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: Issues - issues"))
}

// Issue is the resolver for the issue field.
func (r *queryResolver) Issue(ctx context.Context, repo string, number int64) (*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: Issue - issue"))
}

// PullRequest is the resolver for the pullRequest field.
func (r *queryResolver) PullRequest(ctx context.Context, repo string, number int64) (*graphql1.PullRequest, error) {
	panic(fmt.Errorf("not implemented: PullRequest - pullRequest"))
}

// WorkflowRuns is the resolver for the workflowRuns field.
func (r *queryResolver) WorkflowRuns(ctx context.Context, repo string) ([]*graphql1.WorkflowRun, error) {
	panic(fmt.Errorf("not implemented: WorkflowRuns - workflowRuns"))
}

// Repos is the resolver for the repos field.
func (r *queryResolver) Repos(ctx context.Context) ([]*graphql1.Repo, error) {
	panic(fmt.Errorf("not implemented: Repos - repos"))
}

// Git is the resolver for the git field.
func (r *queryResolver) Git(ctx context.Context, worktreeID string, args []string) (any, error) {
	panic(fmt.Errorf("not implemented: Git - git"))
}

// Host is the resolver for the host field.
func (r *queryResolver) Host(ctx context.Context) (*graphql1.Host, error) {
	panic(fmt.Errorf("not implemented: Host - host"))
}

// Hosts is the resolver for the hosts field.
func (r *queryResolver) Hosts(ctx context.Context) ([]*graphql1.Host, error) {
	panic(fmt.Errorf("not implemented: Hosts - hosts"))
}

// Peers is the resolver for the peers field.
func (r *queryResolver) Peers(ctx context.Context) ([]*graphql1.Host, error) {
	panic(fmt.Errorf("not implemented: Peers - peers"))
}

// HostServices is the resolver for the hostServices field.
func (r *queryResolver) HostServices(ctx context.Context, filter *graphql1.HostServiceFilter) ([]*graphql1.HostService, error) {
	panic(fmt.Errorf("not implemented: HostServices - hostServices"))
}

// HostServiceCtl is the resolver for the hostServiceCtl field.
func (r *queryResolver) HostServiceCtl(ctx context.Context, host string, args []string) (any, error) {
	panic(fmt.Errorf("not implemented: HostServiceCtl - hostServiceCtl"))
}

// Ps is the resolver for the ps field.
func (r *queryResolver) Ps(ctx context.Context, tool graphql1.PsTool, args []string) (any, error) {
	panic(fmt.Errorf("not implemented: Ps - ps"))
}

// TmuxServer is the resolver for the tmuxServer field.
func (r *queryResolver) TmuxServer(ctx context.Context) (*graphql1.TmuxServer, error) {
	panic(fmt.Errorf("not implemented: TmuxServer - tmuxServer"))
}

// TmuxSessions is the resolver for the tmuxSessions field.
func (r *queryResolver) TmuxSessions(ctx context.Context, filter *graphql1.TmuxSessionFilter) ([]*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: TmuxSessions - tmuxSessions"))
}

// TmuxPanes is the resolver for the tmuxPanes field.
func (r *queryResolver) TmuxPanes(ctx context.Context, filter *graphql1.TmuxPaneFilter) ([]*graphql1.TmuxPane, error) {
	panic(fmt.Errorf("not implemented: TmuxPanes - tmuxPanes"))
}

// Tmux is the resolver for the tmux field.
func (r *queryResolver) Tmux(ctx context.Context, args []string) (any, error) {
	panic(fmt.Errorf("not implemented: Tmux - tmux"))
}

// WorkView is the resolver for the workView field.
func (r *queryResolver) WorkView(ctx context.Context) (*graphql1.WorkView, error) {
	panic(fmt.Errorf("not implemented: WorkView - workView"))
}

// Worktrees is the resolver for the worktrees field.
func (r *repoResolver) Worktrees(ctx context.Context, obj *graphql1.Repo) ([]*graphql1.Worktree, error) {
	panic(fmt.Errorf("not implemented: Worktrees - worktrees"))
}

// NodeChanged is the resolver for the nodeChanged field.
func (r *subscriptionResolver) NodeChanged(ctx context.Context, id string) (<-chan graphql1.Node, error) {
	panic(fmt.Errorf("not implemented: NodeChanged - nodeChanged"))
}

// Peer is the resolver for the peer field.
func (r *subscriptionResolver) Peer(ctx context.Context, host string) (<-chan graphql1.Node, error) {
	panic(fmt.Errorf("not implemented: Peer - peer"))
}

// ConversationChanged is the resolver for the conversationChanged field.
func (r *subscriptionResolver) ConversationChanged(ctx context.Context, sessionUUID string) (<-chan *graphql1.Conversation, error) {
	panic(fmt.Errorf("not implemented: ConversationChanged - conversationChanged"))
}

// PullRequestChanged is the resolver for the pullRequestChanged field.
func (r *subscriptionResolver) PullRequestChanged(ctx context.Context, repo string, number int64) (<-chan *graphql1.PullRequest, error) {
	panic(fmt.Errorf("not implemented: PullRequestChanged - pullRequestChanged"))
}

// RunChanged is the resolver for the runChanged field.
func (r *subscriptionResolver) RunChanged(ctx context.Context, repo string, branch string) (<-chan *graphql1.WorkflowRun, error) {
	panic(fmt.Errorf("not implemented: RunChanged - runChanged"))
}

// WorktreeChanged is the resolver for the worktreeChanged field.
func (r *subscriptionResolver) WorktreeChanged(ctx context.Context, repo string) (<-chan []*graphql1.Worktree, error) {
	panic(fmt.Errorf("not implemented: WorktreeChanged - worktreeChanged"))
}

// Processes is the resolver for the processes field.
func (r *subscriptionResolver) Processes(ctx context.Context) (<-chan []*graphql1.Process, error) {
	panic(fmt.Errorf("not implemented: Processes - processes"))
}

// TmuxSessionsChanged is the resolver for the tmuxSessionsChanged field.
func (r *subscriptionResolver) TmuxSessionsChanged(ctx context.Context) (<-chan []*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: TmuxSessionsChanged - tmuxSessionsChanged"))
}

// Server is the resolver for the server field.
func (r *tmuxClientResolver) Server(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxServer, error) {
	panic(fmt.Errorf("not implemented: Server - server"))
}

// Session is the resolver for the session field.
func (r *tmuxClientResolver) Session(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: Session - session"))
}

// Tty is the resolver for the tty field.
func (r *tmuxClientResolver) Tty(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	panic(fmt.Errorf("not implemented: Tty - tty"))
}

// Hostname is the resolver for the hostname field.
func (r *tmuxClientResolver) Hostname(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	panic(fmt.Errorf("not implemented: Hostname - hostname"))
}

// TermName is the resolver for the termName field.
func (r *tmuxClientResolver) TermName(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	panic(fmt.Errorf("not implemented: TermName - termName"))
}

// AttachedAt is the resolver for the attachedAt field.
func (r *tmuxClientResolver) AttachedAt(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	panic(fmt.Errorf("not implemented: AttachedAt - attachedAt"))
}

// LastActivityAt is the resolver for the lastActivityAt field.
func (r *tmuxClientResolver) LastActivityAt(ctx context.Context, obj *graphql1.TmuxClient) (*string, error) {
	panic(fmt.Errorf("not implemented: LastActivityAt - lastActivityAt"))
}

// Readonly is the resolver for the readonly field.
func (r *tmuxClientResolver) Readonly(ctx context.Context, obj *graphql1.TmuxClient) (bool, error) {
	panic(fmt.Errorf("not implemented: Readonly - readonly"))
}

// CurrentWindow is the resolver for the currentWindow field.
func (r *tmuxClientResolver) CurrentWindow(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxWindow, error) {
	panic(fmt.Errorf("not implemented: CurrentWindow - currentWindow"))
}

// CurrentPane is the resolver for the currentPane field.
func (r *tmuxClientResolver) CurrentPane(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxPane, error) {
	panic(fmt.Errorf("not implemented: CurrentPane - currentPane"))
}

// Window is the resolver for the window field.
func (r *tmuxPaneResolver) Window(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.TmuxWindow, error) {
	panic(fmt.Errorf("not implemented: Window - window"))
}

// Title is the resolver for the title field.
func (r *tmuxPaneResolver) Title(ctx context.Context, obj *graphql1.TmuxPane) (string, error) {
	panic(fmt.Errorf("not implemented: Title - title"))
}

// CurrentCommand is the resolver for the currentCommand field.
func (r *tmuxPaneResolver) CurrentCommand(ctx context.Context, obj *graphql1.TmuxPane) (string, error) {
	panic(fmt.Errorf("not implemented: CurrentCommand - currentCommand"))
}

// CurrentPid is the resolver for the currentPid field.
func (r *tmuxPaneResolver) CurrentPid(ctx context.Context, obj *graphql1.TmuxPane) (*int64, error) {
	panic(fmt.Errorf("not implemented: CurrentPid - currentPid"))
}

// Width is the resolver for the width field.
func (r *tmuxPaneResolver) Width(ctx context.Context, obj *graphql1.TmuxPane) (int64, error) {
	panic(fmt.Errorf("not implemented: Width - width"))
}

// Height is the resolver for the height field.
func (r *tmuxPaneResolver) Height(ctx context.Context, obj *graphql1.TmuxPane) (int64, error) {
	panic(fmt.Errorf("not implemented: Height - height"))
}

// Dead is the resolver for the dead field.
func (r *tmuxPaneResolver) Dead(ctx context.Context, obj *graphql1.TmuxPane) (bool, error) {
	panic(fmt.Errorf("not implemented: Dead - dead"))
}

// WatchingClients is the resolver for the watchingClients field.
func (r *tmuxPaneResolver) WatchingClients(ctx context.Context, obj *graphql1.TmuxPane) ([]*graphql1.TmuxClient, error) {
	panic(fmt.Errorf("not implemented: WatchingClients - watchingClients"))
}

// Process is the resolver for the process field.
func (r *tmuxPaneResolver) Process(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.Process, error) {
	panic(fmt.Errorf("not implemented: Process - process"))
}

// ClaudeInstance is the resolver for the claudeInstance field.
func (r *tmuxPaneResolver) ClaudeInstance(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.ClaudeInstance, error) {
	panic(fmt.Errorf("not implemented: ClaudeInstance - claudeInstance"))
}

// Content is the resolver for the content field.
func (r *tmuxPaneResolver) Content(ctx context.Context, obj *graphql1.TmuxPane, lines *int64, stripAnsi *bool) (string, error) {
	panic(fmt.Errorf("not implemented: Content - content"))
}

// ContentRange is the resolver for the contentRange field.
func (r *tmuxPaneResolver) ContentRange(ctx context.Context, obj *graphql1.TmuxPane, startLine int64, endLine int64, stripAnsi *bool) (string, error) {
	panic(fmt.Errorf("not implemented: ContentRange - contentRange"))
}

// ContentFull is the resolver for the contentFull field.
func (r *tmuxPaneResolver) ContentFull(ctx context.Context, obj *graphql1.TmuxPane, stripAnsi *bool) (string, error) {
	panic(fmt.Errorf("not implemented: ContentFull - contentFull"))
}

// Pid is the resolver for the pid field.
func (r *tmuxServerResolver) Pid(ctx context.Context, obj *graphql1.TmuxServer) (*int64, error) {
	panic(fmt.Errorf("not implemented: Pid - pid"))
}

// Alive is the resolver for the alive field.
func (r *tmuxServerResolver) Alive(ctx context.Context, obj *graphql1.TmuxServer) (bool, error) {
	panic(fmt.Errorf("not implemented: Alive - alive"))
}

// Sessions is the resolver for the sessions field.
func (r *tmuxServerResolver) Sessions(ctx context.Context, obj *graphql1.TmuxServer, sort *graphql1.TmuxSessionSort) ([]*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: Sessions - sessions"))
}

// Clients is the resolver for the clients field.
func (r *tmuxServerResolver) Clients(ctx context.Context, obj *graphql1.TmuxServer) ([]*graphql1.TmuxClient, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// Server is the resolver for the server field.
func (r *tmuxSessionResolver) Server(ctx context.Context, obj *graphql1.TmuxSession) (*graphql1.TmuxServer, error) {
	panic(fmt.Errorf("not implemented: Server - server"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *tmuxSessionResolver) CreatedAt(ctx context.Context, obj *graphql1.TmuxSession) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Attached is the resolver for the attached field.
func (r *tmuxSessionResolver) Attached(ctx context.Context, obj *graphql1.TmuxSession) (bool, error) {
	panic(fmt.Errorf("not implemented: Attached - attached"))
}

// ActiveAttached is the resolver for the activeAttached field.
func (r *tmuxSessionResolver) ActiveAttached(ctx context.Context, obj *graphql1.TmuxSession) (bool, error) {
	panic(fmt.Errorf("not implemented: ActiveAttached - activeAttached"))
}

// AttachedClients is the resolver for the attachedClients field.
func (r *tmuxSessionResolver) AttachedClients(ctx context.Context, obj *graphql1.TmuxSession) ([]*graphql1.TmuxClient, error) {
	panic(fmt.Errorf("not implemented: AttachedClients - attachedClients"))
}

// LastActivityAt is the resolver for the lastActivityAt field.
func (r *tmuxSessionResolver) LastActivityAt(ctx context.Context, obj *graphql1.TmuxSession) (*string, error) {
	panic(fmt.Errorf("not implemented: LastActivityAt - lastActivityAt"))
}

// Windows is the resolver for the windows field.
func (r *tmuxSessionResolver) Windows(ctx context.Context, obj *graphql1.TmuxSession) ([]*graphql1.TmuxWindow, error) {
	panic(fmt.Errorf("not implemented: Windows - windows"))
}

// CurrentWindow is the resolver for the currentWindow field.
func (r *tmuxSessionResolver) CurrentWindow(ctx context.Context, obj *graphql1.TmuxSession) (*graphql1.TmuxWindow, error) {
	panic(fmt.Errorf("not implemented: CurrentWindow - currentWindow"))
}

// Session is the resolver for the session field.
func (r *tmuxWindowResolver) Session(ctx context.Context, obj *graphql1.TmuxWindow) (*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: Session - session"))
}

// Name is the resolver for the name field.
func (r *tmuxWindowResolver) Name(ctx context.Context, obj *graphql1.TmuxWindow) (string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Active is the resolver for the active field.
func (r *tmuxWindowResolver) Active(ctx context.Context, obj *graphql1.TmuxWindow) (bool, error) {
	panic(fmt.Errorf("not implemented: Active - active"))
}

// Panes is the resolver for the panes field.
func (r *tmuxWindowResolver) Panes(ctx context.Context, obj *graphql1.TmuxWindow) ([]*graphql1.TmuxPane, error) {
	panic(fmt.Errorf("not implemented: Panes - panes"))
}

// CurrentPane is the resolver for the currentPane field.
func (r *tmuxWindowResolver) CurrentPane(ctx context.Context, obj *graphql1.TmuxWindow) (*graphql1.TmuxPane, error) {
	panic(fmt.Errorf("not implemented: CurrentPane - currentPane"))
}

// Host is the resolver for the host field.
func (r *worktreeResolver) Host(ctx context.Context, obj *graphql1.Worktree) (string, error) {
	panic(fmt.Errorf("not implemented: Host - host"))
}

// Repo is the resolver for the repo field.
func (r *worktreeResolver) Repo(ctx context.Context, obj *graphql1.Worktree) (*string, error) {
	panic(fmt.Errorf("not implemented: Repo - repo"))
}

// Pr is the resolver for the pr field.
func (r *worktreeResolver) Pr(ctx context.Context, obj *graphql1.Worktree) (*graphql1.PullRequest, error) {
	panic(fmt.Errorf("not implemented: Pr - pr"))
}

// Issue is the resolver for the issue field.
func (r *worktreeResolver) Issue(ctx context.Context, obj *graphql1.Worktree) (*graphql1.Issue, error) {
	panic(fmt.Errorf("not implemented: Issue - issue"))
}

// Processes is the resolver for the processes field.
func (r *worktreeResolver) Processes(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.Process, error) {
	panic(fmt.Errorf("not implemented: Processes - processes"))
}

// TmuxPanes is the resolver for the tmuxPanes field.
func (r *worktreeResolver) TmuxPanes(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.TmuxPane, error) {
	panic(fmt.Errorf("not implemented: TmuxPanes - tmuxPanes"))
}

// TmuxSession is the resolver for the tmuxSession field.
func (r *worktreeResolver) TmuxSession(ctx context.Context, obj *graphql1.Worktree) (*graphql1.TmuxSession, error) {
	panic(fmt.Errorf("not implemented: TmuxSession - tmuxSession"))
}

// ClaudeInstances is the resolver for the claudeInstances field.
func (r *worktreeResolver) ClaudeInstances(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.ClaudeInstance, error) {
	panic(fmt.Errorf("not implemented: ClaudeInstances - claudeInstances"))
}

// ClaudeInstance returns graphql1.ClaudeInstanceResolver implementation.
func (r *Resolver) ClaudeInstance() graphql1.ClaudeInstanceResolver {
	return &claudeInstanceResolver{r}
}

// Host returns graphql1.HostResolver implementation.
func (r *Resolver) Host() graphql1.HostResolver { return &hostResolver{r} }

// Issue returns graphql1.IssueResolver implementation.
func (r *Resolver) Issue() graphql1.IssueResolver { return &issueResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Process returns graphql1.ProcessResolver implementation.
func (r *Resolver) Process() graphql1.ProcessResolver { return &processResolver{r} }

// PullRequest returns graphql1.PullRequestResolver implementation.
func (r *Resolver) PullRequest() graphql1.PullRequestResolver { return &pullRequestResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Repo returns graphql1.RepoResolver implementation.
func (r *Resolver) Repo() graphql1.RepoResolver { return &repoResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

// TmuxClient returns graphql1.TmuxClientResolver implementation.
func (r *Resolver) TmuxClient() graphql1.TmuxClientResolver { return &tmuxClientResolver{r} }

// TmuxPane returns graphql1.TmuxPaneResolver implementation.
func (r *Resolver) TmuxPane() graphql1.TmuxPaneResolver { return &tmuxPaneResolver{r} }

// TmuxServer returns graphql1.TmuxServerResolver implementation.
func (r *Resolver) TmuxServer() graphql1.TmuxServerResolver { return &tmuxServerResolver{r} }

// TmuxSession returns graphql1.TmuxSessionResolver implementation.
func (r *Resolver) TmuxSession() graphql1.TmuxSessionResolver { return &tmuxSessionResolver{r} }

// TmuxWindow returns graphql1.TmuxWindowResolver implementation.
func (r *Resolver) TmuxWindow() graphql1.TmuxWindowResolver { return &tmuxWindowResolver{r} }

// Worktree returns graphql1.WorktreeResolver implementation.
func (r *Resolver) Worktree() graphql1.WorktreeResolver { return &worktreeResolver{r} }

type claudeInstanceResolver struct{ *Resolver }
type hostResolver struct{ *Resolver }
type issueResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type processResolver struct{ *Resolver }
type pullRequestResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type repoResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tmuxClientResolver struct{ *Resolver }
type tmuxPaneResolver struct{ *Resolver }
type tmuxServerResolver struct{ *Resolver }
type tmuxSessionResolver struct{ *Resolver }
type tmuxWindowResolver struct{ *Resolver }
type worktreeResolver struct{ *Resolver }
