package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"sort"
	"time"

	graphql1 "github.com/drewdrewthis/git-orchard-rs/internal/server/graphql"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*graphql1.Health, error) {
	uptime := int64(time.Since(r.StartedAt).Round(time.Second).Seconds())
	return &graphql1.Health{
		Status:  "ok",
		UptimeS: uptime,
	}, nil
}

// Host is the resolver for the host field.
func (r *queryResolver) Host(ctx context.Context) (*graphql1.Host, error) {
	if r.HostProvider == nil {
		return nil, fmt.Errorf("host provider not initialised")
	}
	h, _, err := r.HostProvider.Get(ctx, r.HostProvider.LocalID())
	if err != nil {
		return nil, fmt.Errorf("host: %w", err)
	}
	return h, nil
}

// Hosts is the resolver for the hosts field.
func (r *queryResolver) Hosts(ctx context.Context) ([]*graphql1.Host, error) {
	h, err := r.Query().Host(ctx)
	if err != nil {
		return nil, err
	}
	return []*graphql1.Host{h}, nil
}

// Projects is the resolver for the projects field. It returns the
// in-memory cached snapshot from the config provider. Order is stable
// (by id) so consumers get reproducible output.
func (r *queryResolver) Projects(ctx context.Context) ([]*graphql1.Project, error) {
	if r.ProjectsProvider == nil {
		return nil, fmt.Errorf("projects provider not wired: daemon misconfigured")
	}
	rows, err := r.ProjectsProvider.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	out := make([]*graphql1.Project, 0, len(rows))
	for _, row := range rows {
		out = append(out, &graphql1.Project{
			ID:        string(row.ID),
			Directory: row.Directory,
			Name:      row.Name,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
