package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"os/exec"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/drewdrewthis/orchardist/daemon/git"
	graphql1 "github.com/drewdrewthis/orchardist/internal/server/graphql"
	"github.com/drewdrewthis/orchardist/internal/server/loaders"
	"github.com/drewdrewthis/orchardist/internal/server/providers/claudeaccount"
	"github.com/drewdrewthis/orchardist/internal/server/providers/gh"
	"github.com/drewdrewthis/orchardist/internal/server/providers/peerproxy"
	"github.com/drewdrewthis/orchardist/internal/server/providers/ps"
	"github.com/drewdrewthis/orchardist/internal/server/providers/tmux"
)

// Worktree resolves ClaudeInstance.worktree (#540): the deepest worktree
// whose path contains the resolved process cwd. Returns nil when no
// process can be matched, no cwd resolves, or no worktree contains the
// cwd. Mirrors the cwd→worktree match used by tmuxPane and Process.
func (r *claudeInstanceResolver) Worktree(ctx context.Context, obj *graphql1.ClaudeInstance) (*graphql1.Worktree, error) {
	if obj == nil {
		return nil, nil
	}
	// Reuse the same cwd-resolution path as Worktree.claudeInstances so
	// the two halves of the join agree.
	wr := &worktreeResolver{r.Resolver}
	cwd := loadInstanceCwd(ctx, wr, obj)
	if cwd == "" {
		return nil, nil
	}
	return findWorktreeForCwd(ctx, r.Resolver, cwd)
}

// Conversation resolves ClaudeInstance.conversation (#540): looks up
// the cached Conversation by the instance's sessionUuid in the
// claudeprojects provider. Returns nil when the instance has no
// sessionUuid, the provider is unwired, or no JSONL has yet been
// observed for that uuid. Lets clients pull customTitle / agentName /
// lastSeenAt without a separate `conversations` query + uuid map.
func (r *claudeInstanceResolver) Conversation(ctx context.Context, obj *graphql1.ClaudeInstance) (*graphql1.Conversation, error) {
	if obj == nil || obj.SessionUUID == nil || *obj.SessionUUID == "" {
		return nil, nil
	}
	if r.ClaudeProjects == nil {
		return nil, nil
	}
	conv, ok := r.ClaudeProjects.GetBySessionUUID(ctx, *obj.SessionUUID)
	if !ok {
		return nil, nil
	}
	return r.ClaudeProjects.ToGraphQL(conv), nil
}

// Peers is the resolver for the peers field.
func (r *hostResolver) Peers(ctx context.Context, obj *graphql1.Host) ([]*graphql1.Host, error) {
	if r.PeerProxy == nil {
		return []*graphql1.Host{}, nil
	}
	if !isLocalHostNode(r, obj) {
		return []*graphql1.Host{}, nil
	}
	cfgs := r.PeerProxy.Peers()
	out := make([]*graphql1.Host, 0, len(cfgs))
	for _, cfg := range cfgs {
		reachable, lastReachedAt, _ := r.PeerProxy.Reachability(cfg.Name)
		addr := cfg.Address
		host := &graphql1.Host{
			ID:         "Host:" + cfg.Name,
			MachineID:  cfg.Name,
			Hostname:   cfg.Name,
			Os:         "remote",
			Reachable:  reachable,
			Address:    &addr,
			Peers:      []*graphql1.Host{},
			LastSeenAt: peerLastSeen(lastReachedAt),
		}
		if cfg.Purpose != "" {
			p := cfg.Purpose
			host.Purpose = &p
		}
		out = append(out, host)
	}
	return out, nil
}

// Version is the resolver for the host.version field (#417 AC3).
//
// Local host: returns DaemonVersion (set at boot via WithVersion / -ldflags).
// Peer host: returns the version the peerproxy provider cached on the
// most recent successful probe, or nil when the peer has never been reached.
// Null is the legitimate "unknown" — no error is raised.
func (r *hostResolver) Version(ctx context.Context, obj *graphql1.Host) (*string, error) {
	if isLocalHostNode(r, obj) {
		v := r.DaemonVersion
		return &v, nil
	}
	// Peer host — return the version cached by the probe, or nil.
	if r.PeerProxy == nil {
		return nil, nil
	}
	return r.PeerProxy.PeerVersion(obj.MachineID), nil
}

// Processes is the resolver for the host.processes field. Local host: in-process ps. Peer Host: federate via peerproxy (#465 — never return local ps for a peer).
func (r *hostResolver) Processes(ctx context.Context, obj *graphql1.Host, filter *graphql1.ProcessFilter) ([]*graphql1.Process, error) {
	if isLocalHostNode(r, obj) {
		if r.PS == nil {
			return nil, fmt.Errorf("ps provider not wired")
		}
		all := r.PS.List()
		filtered := applyProcessFilter(ctx, r.PS, all, filter)
		hostID := r.PS.HostID()
		out := make([]*graphql1.Process, 0, len(filtered))
		for i := range filtered {
			out = append(out, projectProcess(&filtered[i], hostID))
		}
		return out, nil
	}
	return federatePeerProcesses(ctx, r, obj, filter)
}

// Labels is the resolver for the issue.labels field. The gh provider's GetIssue already loads labels from the REST payload and strips orchard phase labels; the resolver only projects to the GraphQL type.
func (r *issueResolver) Labels(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Label, error) {
	if r.GH == nil || obj == nil {
		return []*graphql1.Label{}, nil
	}
	owner, name, number, ok := splitGHNodeID(obj.ID, "Issue:")
	if !ok {
		return []*graphql1.Label{}, nil
	}
	issue, err := r.GH.GetIssue(ctx, gh.IssueKey{Owner: owner, Name: name, Number: number})
	if err != nil {
		return nil, err
	}
	return toGraphQLLabels(issue.Labels), nil
}

// BlockedByIssues is the resolver for the issue.blockedByIssues field (#563).
// Delegates to issueDependencies which loads all four dependency edges
// in one round-trip and caches the result.
func (r *issueResolver) BlockedByIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	deps, err := r.issueDependencies(ctx, obj)
	if err != nil || deps == nil {
		return []*graphql1.Issue{}, err
	}
	return issueRefsToGraphQL(deps.BlockedBy), nil
}

// BlockingIssues is the resolver for the issue.blockingIssues field (#563).
func (r *issueResolver) BlockingIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	deps, err := r.issueDependencies(ctx, obj)
	if err != nil || deps == nil {
		return []*graphql1.Issue{}, err
	}
	return issueRefsToGraphQL(deps.Blocking), nil
}

// SubIssues is the resolver for the issue.subIssues field (#563).
func (r *issueResolver) SubIssues(ctx context.Context, obj *graphql1.Issue) ([]*graphql1.Issue, error) {
	deps, err := r.issueDependencies(ctx, obj)
	if err != nil || deps == nil {
		return []*graphql1.Issue{}, err
	}
	return issueRefsToGraphQL(deps.SubIssues), nil
}

// ParentIssue is the resolver for the issue.parentIssue field (#563).
func (r *issueResolver) ParentIssue(ctx context.Context, obj *graphql1.Issue) (*graphql1.Issue, error) {
	deps, err := r.issueDependencies(ctx, obj)
	if err != nil || deps == nil || deps.Parent == nil {
		return nil, err
	}
	out := issueRefToGraphQL(*deps.Parent)
	return out, nil
}

// SendTextToPane is the resolver for the sendTextToPane field.
//
// Two-step `tmux send-keys`: first `-l <text>` writes the chat message
// literally (no shell interpretation, safe with backticks / magic
// strings); then a separate `Enter` keypress submits. Mirrors the
// desktop app's Tauri command in crates/orchard-gui/src-tauri/src/commands.rs.
// A short gap between the two keeps the Enter from racing the text into the
// same input batch (which Claude's TUI swallows as a pasted newline).
func (r *mutationResolver) SendTextToPane(ctx context.Context, paneID string, text string) (bool, error) {
	if paneID == "" {
		return false, fmt.Errorf("paneId is empty")
	}
	if text == "" {
		return false, fmt.Errorf("text is empty")
	}
	// Two separate send-keys with a short gap. First `-l <text>` writes the
	// message literally (no shell interpretation, safe with backticks); a
	// brief sleep lets Claude's TUI flush the paste-like input; then a
	// discrete `Enter` keypress submits. Collapsing these into one
	// invocation (or firing them back-to-back with no gap) makes the Enter
	// race the text into the same input batch — Claude's TUI then treats it
	// as a pasted newline rather than a submit, so the message lands in the
	// composer box but is never sent. Observed on a freshly-booted REPL: the
	// text appeared at the `❯` prompt but Claude never processed it until a
	// manual Enter arrived. Mirrors the desktop Tauri command's gap.
	if out, err := exec.CommandContext(ctx, "tmux", "send-keys", "-t", paneID, "-l", text).CombinedOutput(); err != nil {
		return false, fmt.Errorf("tmux send-keys (text): %w: %s", err, strings.TrimSpace(string(out)))
	}
	// 250ms clears Claude Code's paste-coalesce window. A shorter gap
	// (tested at 75ms) intermittently lets the Enter get absorbed into the
	// paste burst on a freshly-booted REPL, leaving the message unsent.
	// select (not a bare time.Sleep) so a cancelled request returns promptly
	// instead of blocking the goroutine for the full window.
	select {
	case <-time.After(250 * time.Millisecond):
	case <-ctx.Done():
		return false, ctx.Err()
	}
	if out, err := exec.CommandContext(ctx, "tmux", "send-keys", "-t", paneID, "Enter").CombinedOutput(); err != nil {
		return false, fmt.Errorf("tmux send-keys (enter): %w: %s", err, strings.TrimSpace(string(out)))
	}
	return true, nil
}

// LaunchSession is the resolver for the launchSession field. The tmux +
// claude-launch logic lives in launch.go (launchClaudeSession) so this
// gqlgen-managed file stays a thin projection.
func (r *mutationResolver) LaunchSession(ctx context.Context, input graphql1.LaunchSessionInput) (*graphql1.LaunchSessionResult, error) {
	return launchClaudeSession(ctx, input)
}

// WorktreeRemove is the resolver for the worktreeRemove field (#693 step 1).
// Delegates to the git-domain MutationResolver which execs
// scripts/git/worktree-remove.sh --json (L1/L5).
func (r *mutationResolver) WorktreeRemove(ctx context.Context, input graphql1.WorktreeRemoveInput) (*graphql1.WorktreeMutationResult, error) {
	if r.GitMutations == nil {
		notConfigured := "NOT_CONFIGURED"
		notConfiguredMsg := "git mutations resolver not configured"
		return &graphql1.WorktreeMutationResult{
			Ok:      false,
			ErrCode: &notConfigured,
			ErrMsg:  &notConfiguredMsg,
		}, nil
	}
	domainInput := git.WorktreeRemoveInput{
		WorktreeID: input.WorktreeID,
	}
	if input.Force != nil {
		domainInput.Force = *input.Force
	}
	// AC-G1: thread active-session identity from the caller through to the script.
	// The daemon never reads $TMUX or calls current_session_name() — identity
	// is always caller-supplied so the guard is not defeated by the daemon move.
	if input.ActiveSession != nil {
		domainInput.ActiveSession = *input.ActiveSession
	}
	if input.ActiveCwd != nil {
		domainInput.ActiveCwd = *input.ActiveCwd
	}
	result, err := r.GitMutations.WorktreeRemove(ctx, domainInput)
	if err != nil {
		return nil, err
	}
	out := &graphql1.WorktreeMutationResult{Ok: result.OK}
	if !result.OK {
		errCode := result.ErrCode
		errMsg := result.ErrMsg
		out.ErrCode = &errCode
		out.ErrMsg = &errMsg
	}
	return out, nil
}

// WorktreesCleanup is the resolver for the worktreesCleanup field (#693 step 6).
// Delegates to the git-domain MutationResolver which runs worktree-remove.sh
// for each worktree, serialized under a daemon-side mutex (AC-G5, L1/L5).
//
// AC2: caller passes exactly the stale-set IDs; this resolver acts on exactly
// that set and never touches worktrees it was not given.
// AC8: partial-failure isolated per entry; all IDs are attempted.
// AC9: idempotent — already-removed worktrees return alreadyRemoved:true.
// AC-G5: serialize via cleanupMu; race loser gets alreadyRemoved:true entries.
// AC10: malformed input → typed INVALID_INPUT at resolver boundary, not a script crash.
func (r *mutationResolver) WorktreesCleanup(ctx context.Context, input graphql1.WorktreesCleanupInput) (*graphql1.WorktreesCleanupResult, error) {
	if r.GitMutations == nil {
		notConfigured := "NOT_CONFIGURED"
		notConfiguredMsg := "git mutations resolver not configured"
		return &graphql1.WorktreesCleanupResult{
			Ok:      false,
			ErrCode: &notConfigured,
			ErrMsg:  &notConfiguredMsg,
			Entries: []*graphql1.WorktreeCleanupEntry{},
		}, nil
	}

	// Project GraphQL input → domain input.
	domainInput := git.WorktreesCleanupInput{
		WorktreeIDs: input.WorktreeIds,
	}
	if input.Force != nil {
		domainInput.Force = *input.Force
	}
	if input.ActiveSession != nil {
		domainInput.ActiveSession = *input.ActiveSession
	}
	if input.ActiveCwd != nil {
		domainInput.ActiveCwd = *input.ActiveCwd
	}
	if input.BaseBranch != nil {
		domainInput.BaseBranch = *input.BaseBranch
	}
	if input.Protected != nil {
		domainInput.Protected = *input.Protected
	}
	// AC-G3: project per-worktree session names from the GraphQL input.
	// The generated field is []*string (nullable elements); flatten to []string
	// using "" for nil entries — the domain layer treats empty strings as absent.
	if len(input.SessionNames) > 0 {
		names := make([]string, len(input.SessionNames))
		for i, p := range input.SessionNames {
			if p != nil {
				names[i] = *p
			}
		}
		domainInput.SessionNames = names
	}

	result, err := r.GitMutations.WorktreesCleanup(ctx, domainInput)
	if err != nil {
		return nil, err
	}

	// Project domain result → GraphQL result.
	out := &graphql1.WorktreesCleanupResult{
		Ok:      result.OK,
		Entries: make([]*graphql1.WorktreeCleanupEntry, 0, len(result.Entries)),
	}
	if !result.OK {
		errCode := result.ErrCode
		errMsg := result.ErrMsg
		out.ErrCode = &errCode
		out.ErrMsg = &errMsg
	}
	for _, e := range result.Entries {
		entry := &graphql1.WorktreeCleanupEntry{
			WorktreeID: e.WorktreeID,
			Ok:         e.OK,
			Warnings:   e.Warnings,
		}
		if e.Warnings == nil {
			entry.Warnings = []string{}
		}
		if e.Stage != "" {
			s := e.Stage
			entry.Stage = &s
		}
		if e.Message != "" {
			m := e.Message
			entry.Message = &m
		}
		if e.AlreadyRemoved {
			t := true
			entry.AlreadyRemoved = &t
		}
		out.Entries = append(out.Entries, entry)
	}
	return out, nil
}

// Host is the resolver for the process.host field.
func (r *processResolver) Host(ctx context.Context, obj *graphql1.Process) (*graphql1.Host, error) {
	hostID, _ := splitProcessNodeID(obj.ID)
	return &graphql1.Host{ID: hostID}, nil
}

// Args is the resolver for the process.args field.
func (r *processResolver) Args(ctx context.Context, obj *graphql1.Process) ([]string, error) {
	if r.PS == nil {
		return nil, nil
	}
	pid := int(obj.Pid)
	got, err := r.PS.LoadArgs(ctx, []int{pid})
	if err != nil {
		return nil, err
	}
	return got[pid], nil
}

// Cwd is the resolver for the process.cwd field.
func (r *processResolver) Cwd(ctx context.Context, obj *graphql1.Process) (*string, error) {
	if r.PS == nil {
		return nil, nil
	}
	cwd, err := r.PS.LoadCwd(ctx, int(obj.Pid))
	if err != nil {
		return nil, err
	}
	if cwd == "" {
		return nil, nil
	}
	return &cwd, nil
}

// Worktree is the resolver for the process.worktree field.
func (r *processResolver) Worktree(ctx context.Context, obj *graphql1.Process) (*graphql1.Worktree, error) {
	return nil, nil
}

// ClaudeInstance is the resolver for the process.claudeInstance field.
func (r *processResolver) ClaudeInstance(ctx context.Context, obj *graphql1.Process) (*graphql1.ClaudeInstance, error) {
	return nil, nil
}

// Mergeable is the resolver for the pullRequest.mergeable field. Routes
// through the PullRequestEnrichment dataloader so all enrichment calls
// within one GraphQL request coalesce into one HTTP call per repository.
func (r *pullRequestResolver) Mergeable(ctx context.Context, obj *graphql1.PullRequest) (graphql1.MergeableState, error) {
	key, ok := prKeyFromGraphQL(r.Resolver, obj)
	if !ok {
		return graphql1.MergeableStateUnknown, nil
	}
	pr, err := enrichPR(ctx, r.Resolver, key)
	if err != nil {
		return graphql1.MergeableStateUnknown, err
	}
	return mapMergeableState(pr.Mergeable), nil
}

// MergeStateStatus is the resolver for the pullRequest.mergeStateStatus field.
func (r *pullRequestResolver) MergeStateStatus(ctx context.Context, obj *graphql1.PullRequest) (string, error) {
	key, ok := prKeyFromGraphQL(r.Resolver, obj)
	if !ok {
		return "", nil
	}
	pr, err := enrichPR(ctx, r.Resolver, key)
	if err != nil {
		return "", err
	}
	return pr.MergeStateStatus, nil
}

// ReviewDecision is the resolver for the pullRequest.reviewDecision field.
func (r *pullRequestResolver) ReviewDecision(ctx context.Context, obj *graphql1.PullRequest) (*graphql1.ReviewDecisionEnum, error) {
	key, ok := prKeyFromGraphQL(r.Resolver, obj)
	if !ok {
		return nil, nil
	}
	pr, err := enrichPR(ctx, r.Resolver, key)
	if err != nil {
		return nil, err
	}
	return mapReviewDecision(pr.ReviewDecision), nil
}

// StatusCheckRollup is the resolver for the pullRequest.statusCheckRollup field.
func (r *pullRequestResolver) StatusCheckRollup(ctx context.Context, obj *graphql1.PullRequest) (graphql1.CiStatus, error) {
	key, ok := prKeyFromGraphQL(r.Resolver, obj)
	if !ok {
		return graphql1.CiStatusUnknown, nil
	}
	pr, err := enrichPR(ctx, r.Resolver, key)
	if err != nil {
		return graphql1.CiStatusUnknown, err
	}
	return mapCiStatus(pr.StatusCheckRollup), nil
}

// Labels is the resolver for the pullRequest.labels field. Returns user-assigned labels with orchard phase labels excluded; phase labels are filtered upstream by the gh provider's enrichment path.
func (r *pullRequestResolver) Labels(ctx context.Context, obj *graphql1.PullRequest) ([]*graphql1.Label, error) {
	key, ok := prKeyFromGraphQL(r.Resolver, obj)
	if !ok {
		return []*graphql1.Label{}, nil
	}
	pr, err := enrichPR(ctx, r.Resolver, key)
	if err != nil {
		return nil, err
	}
	return toGraphQLLabels(pr.Labels), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*graphql1.Health, error) {
	uptime := int64(time.Since(r.StartedAt).Round(time.Second).Seconds())
	return &graphql1.Health{
		Status:  "ok",
		UptimeS: uptime,
	}, nil
}

// Host is the resolver for the host field.
func (r *queryResolver) Host(ctx context.Context) (*graphql1.Host, error) {
	var h *graphql1.Host
	if r.HostProvider != nil {
		got, _, err := r.HostProvider.Get(ctx, r.HostProvider.LocalID())
		if err != nil {
			return nil, fmt.Errorf("host: %w", err)
		}
		h = got
	} else if r.PS != nil {
		h = &graphql1.Host{ID: r.PS.HostID()}
	} else if r.HostServiceProvider != nil {
		hostID := r.HostServiceProvider.HostID()
		h = &graphql1.Host{ID: "Host:" + hostID, MachineID: hostID}
	} else {
		return nil, fmt.Errorf("host provider not initialised")
	}
	if r.HostServiceProvider != nil {
		machineID := r.HostServiceProvider.HostID()
		h.HostServices = buildHostServices(ctx, r.HostServiceProvider, machineID)
	}
	return h, nil
}

// Hosts is the resolver for the hosts field.
//
// Returns the live-fleet view: local host + federated peers. The local
// host's purpose is enriched from the peer config when set.
func (r *queryResolver) Hosts(ctx context.Context) ([]*graphql1.Host, error) {
	local, err := r.Query().Host(ctx)
	if err != nil {
		return nil, err
	}
	hosts := []*graphql1.Host{local}
	if r.PeerProxy != nil {
		hostRes := r.Resolver.Host()
		peers, err := hostRes.Peers(ctx, local)
		if err != nil {
			return nil, err
		}
		hosts = append(hosts, peers...)
		if p := purposeForLocalHost(local, r.PeerProxy.Peers()); p != "" {
			local.Purpose = &p
		}
	}
	return hosts, nil
}

// Repos is the resolver for the repos field.
func (r *queryResolver) Repos(ctx context.Context) ([]*graphql1.Repo, error) {
	if r.ReposProvider == nil {
		return nil, fmt.Errorf("repos provider not wired: daemon misconfigured")
	}
	rows, err := r.ReposProvider.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("list repos: %w", err)
	}
	out := make([]*graphql1.Repo, 0, len(rows))
	for _, row := range rows {
		out = append(out, &graphql1.Repo{
			ID:   string(row.ID),
			Slug: row.Slug,
			Path: row.Path,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// TmuxServer is the resolver for the tmuxServer field.
func (r *queryResolver) TmuxServer(ctx context.Context) (*graphql1.TmuxServer, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	info := r.Tmux.Server()
	if !info.Alive {
		return nil, nil
	}
	return projectServer(r.Tmux.Host(), info), nil
}

// TmuxSessions is the resolver for the tmuxSessions field.
func (r *queryResolver) TmuxSessions(ctx context.Context, filter *graphql1.TmuxSessionFilter) ([]*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return []*graphql1.TmuxSession{}, nil
	}
	snap := r.Tmux.Snapshot()
	out := make([]*graphql1.TmuxSession, 0, len(snap.Sessions))
	for _, s := range snap.Sessions {
		if !sessionMatchesFilter(s, filter) {
			continue
		}
		out = append(out, projectSession(s))
	}
	return out, nil
}

// TmuxPanes is the resolver for the tmuxPanes field.
//
// When filter.Cwd or filter.Command are set, the resolver dispatches to the
// PanesByCwd / PanesByCommand dataloaders (ADR-022 axis accessors) and then
// applies remaining filter predicates. When neither is set it falls back to
// the snapshot walk for the cheap, always-available filter axes (paneIdIn,
// currentCommandIn, sessionIn, titleContains, dead).
func (r *queryResolver) TmuxPanes(ctx context.Context, filter *graphql1.TmuxPaneFilter) ([]*graphql1.TmuxPane, error) {
	if r.Tmux == nil {
		return []*graphql1.TmuxPane{}, nil
	}

	host := string(r.Tmux.Host())
	l := loaders.FromContext(ctx)

	// ADR-022 axis: PanesByCwd — delegate to loader when cwd filter is set.
	if filter != nil && filter.Cwd != nil && *filter.Cwd != "" {
		if l != nil {
			result, err := l.PanesByCwd.Load(ctx, loaders.CwdKey{HostID: host, Cwd: *filter.Cwd})()
			if err != nil {
				return nil, err
			}
			// Apply remaining cheap filters.
			var out []*graphql1.TmuxPane
			for _, pn := range result {
				if paneGraphQLMatchesFilter(pn, filter) {
					out = append(out, pn)
				}
			}
			if out == nil {
				return []*graphql1.TmuxPane{}, nil
			}
			return out, nil
		}
		// No loader context — fallback to provider direct call.
		panePsGetter := newResolverPanePsGetter(r.PS)
		raw := r.Tmux.PanesByCwd(host, *filter.Cwd, panePsGetter)
		return projectPanesWithFilter(raw, filter), nil
	}

	// ADR-022 axis: PanesByCommand — delegate to loader when command filter is set.
	if filter != nil && filter.Command != nil && *filter.Command != "" {
		if l != nil {
			result, err := l.PanesByCommand.Load(ctx, loaders.CommandKey{HostID: host, Command: *filter.Command})()
			if err != nil {
				return nil, err
			}
			var out []*graphql1.TmuxPane
			for _, pn := range result {
				if paneGraphQLMatchesFilter(pn, filter) {
					out = append(out, pn)
				}
			}
			if out == nil {
				return []*graphql1.TmuxPane{}, nil
			}
			return out, nil
		}
		panePsGetter := newResolverPanePsGetter(r.PS)
		raw := r.Tmux.PanesByCommand(host, *filter.Command, panePsGetter)
		return projectPanesWithFilter(raw, filter), nil
	}

	// Default: snapshot walk for cheap filter axes.
	snap := r.Tmux.Snapshot()
	out := make([]*graphql1.TmuxPane, 0, len(snap.Panes))
	for _, p := range snap.Panes {
		if !paneMatchesFilter(p, filter) {
			continue
		}
		out = append(out, projectPane(p))
	}
	return out, nil
}

// Conversations is the resolver for the conversations field.
func (r *queryResolver) Conversations(ctx context.Context) ([]*graphql1.Conversation, error) {
	if r.ClaudeProjects == nil {
		return nil, fmt.Errorf("claudeprojects provider not initialised")
	}
	rows, err := r.ClaudeProjects.List(ctx)
	if err != nil {
		return nil, fmt.Errorf("list conversations: %w", err)
	}
	out := make([]*graphql1.Conversation, 0, len(rows))
	for _, c := range rows {
		out = append(out, r.ClaudeProjects.ToGraphQL(c))
	}
	return out, nil
}

// Conversation is the resolver for the conversation field.
func (r *queryResolver) Conversation(ctx context.Context, id string) (*graphql1.Conversation, error) {
	if r.ClaudeProjects == nil {
		return nil, fmt.Errorf("claudeprojects provider not initialised")
	}
	uuid, ok := strings.CutPrefix(id, "Conversation:")
	if !ok || uuid == "" {
		return nil, nil
	}
	keys, err := r.ClaudeProjects.Keys(ctx)
	if err != nil {
		return nil, fmt.Errorf("list conversations: %w", err)
	}
	for _, k := range keys {
		if k.SessionUUID != uuid {
			continue
		}
		c, _, err := r.ClaudeProjects.Get(ctx, k)
		if err != nil {
			return nil, fmt.Errorf("get conversation %q: %w", uuid, err)
		}
		return r.ClaudeProjects.ToGraphQL(c), nil
	}
	return nil, nil
}

// ClaudeAccounts is the resolver for the claudeAccounts field.
func (r *queryResolver) ClaudeAccounts(ctx context.Context) ([]*graphql1.ClaudeAccount, error) {
	if r.ClaudeAccount == nil {
		return nil, fmt.Errorf("claudeaccount provider not initialised")
	}
	rows, err := r.ClaudeAccount.List(ctx)
	if err != nil {
		var notInstalled *claudeaccount.ToolNotInstalledError
		if errors.As(err, &notInstalled) {
			return nil, notInstalled
		}
		return nil, fmt.Errorf("list claude accounts: %w", err)
	}
	out := make([]*graphql1.ClaudeAccount, 0, len(rows))
	for _, a := range rows {
		out = append(out, r.ClaudeAccount.ToGraphQL(a))
	}
	return out, nil
}

// ClaudeInstances is the resolver for the claudeInstances field.
//
// ADR-022 Phase 4/5: pane-first path — a view over Pane nodes filtered by
// command "claude". Uses the PanesByCommand dataloader and
// projectPanesToClaudeInstances to derive state from jsonl snapshots.
func (r *queryResolver) ClaudeInstances(ctx context.Context) ([]*graphql1.ClaudeInstance, error) {
	if r.Tmux == nil {
		return []*graphql1.ClaudeInstance{}, nil
	}
	host := string(r.Tmux.Host())
	l := loaders.FromContext(ctx)
	var panes []*graphql1.TmuxPane
	if l != nil {
		result, err := l.PanesByCommand.Load(ctx, loaders.CommandKey{HostID: host, Command: "claude"})()
		if err != nil {
			return nil, fmt.Errorf("claudeInstances: panes by command: %w", err)
		}
		panes = result
	} else {
		// No loader context — use provider directly (e.g. subscription emissions).
		panePsGetter := newResolverPanePsGetter(r.PS)
		raw := r.Tmux.PanesByCommand(host, "claude", panePsGetter)
		panes = make([]*graphql1.TmuxPane, len(raw))
		for i, pn := range raw {
			panes[i] = projectPaneRich(pn)
		}
	}
	return r.projectPanesToClaudeInstances(ctx, panes), nil
}

// Peers is the resolver for the peers field.
func (r *queryResolver) Peers(ctx context.Context) ([]*graphql1.Host, error) {
	hosts, err := r.Query().Hosts(ctx)
	if err != nil {
		return nil, err
	}
	hostRes := r.Resolver.Host()
	seen := make(map[string]struct{})
	out := make([]*graphql1.Host, 0)
	for _, h := range hosts {
		peers, err := hostRes.Peers(ctx, h)
		if err != nil {
			return nil, err
		}
		for _, p := range peers {
			if p == nil {
				continue
			}
			if _, dup := seen[p.ID]; dup {
				continue
			}
			seen[p.ID] = struct{}{}
			out = append(out, p)
		}
	}
	return out, nil
}

// HostServices is the resolver for the hostServices field.
func (r *queryResolver) HostServices(ctx context.Context, filter *graphql1.HostServiceFilter) ([]*graphql1.HostService, error) {
	hosts, err := r.Query().Hosts(ctx)
	if err != nil {
		return nil, err
	}
	seen := make(map[string]struct{})
	out := make([]*graphql1.HostService, 0)
	for _, h := range hosts {
		for _, svc := range h.HostServices {
			if svc == nil {
				continue
			}
			if !hostServiceMatchesFilter(svc, filter) {
				continue
			}
			if _, dup := seen[svc.ID]; dup {
				continue
			}
			seen[svc.ID] = struct{}{}
			out = append(out, svc)
		}
	}
	return out, nil
}

// PullRequests is the resolver for the pullRequests field.
func (r *queryResolver) PullRequests(ctx context.Context, repo string, state *graphql1.PullRequestState) ([]*graphql1.PullRequest, error) {
	return r.queryPullRequestsResolver(ctx, repo, state)
}

// OpenPullRequests is the resolver for the openPullRequests field.
func (r *queryResolver) OpenPullRequests(ctx context.Context, repo string, author *string) ([]*graphql1.PullRequest, error) {
	return r.queryOpenPullRequestsResolver(ctx, repo, author)
}

// Issues is the resolver for the issues field.
func (r *queryResolver) Issues(ctx context.Context, repo string, state *graphql1.IssueState) ([]*graphql1.Issue, error) {
	return r.queryIssuesResolver(ctx, repo, state)
}

// Issue is the resolver for the issue field.
func (r *queryResolver) Issue(ctx context.Context, repo string, number int64) (*graphql1.Issue, error) {
	return r.queryIssueByNumberResolver(ctx, repo, number)
}

// PullRequest is the resolver for the pullRequest field.
func (r *queryResolver) PullRequest(ctx context.Context, repo string, number int64) (*graphql1.PullRequest, error) {
	return r.queryPullRequestByNumberResolver(ctx, repo, number)
}

// WorkflowRuns is the resolver for the workflowRuns field.
func (r *queryResolver) WorkflowRuns(ctx context.Context, repo string) ([]*graphql1.WorkflowRun, error) {
	return r.queryWorkflowRunsResolver(ctx, repo)
}

// Gh is the resolver for the gh field.
func (r *queryResolver) Gh(ctx context.Context, query string, variables any) (any, error) {
	return r.queryGhResolver(ctx, query, variables)
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (graphql1.Node, error) {
	if r.PeerProxy != nil {
		host := peerproxy.HostFromNodeID(id)
		if host != "" && r.PeerProxy.HasPeer(host) {
			pn, err := r.PeerProxy.Get(ctx, peerproxy.NodeID(id))
			if err != nil {
				return nil, err
			}
			return projectPeerNode(pn)
		}
	}
	node, err := resolveNode(ctx, r.Resolver, id)
	if err == nil {
		return node, nil
	}
	// Fall back to a stub when the local providers are not wired —
	// keeps Query.node well-behaved on minimal daemons (federation
	// fixtures, single-host deployments without tmux/git/etc).
	if stub, stubErr := resolveLocalNode(r, id); stubErr == nil && stub != nil {
		return stub, nil
	}
	return nil, err
}

// SchemaSdl is the resolver for Query.schemaSDL (#469 F10). Returns the daemon's embedded schema.graphql contents so agents can self-describe even without introspection or a source tree on disk.
func (r *queryResolver) SchemaSdl(ctx context.Context) (string, error) {
	return SchemaSDL(), nil
}

// WorkView is the resolver for Query.workView (#469 F6). Walks the local repos-to-worktrees graph and joins each worktree to its open PR, linked issue, processes, and tmux sessions in a single round trip. Uses existing per-type resolvers so semantics match per-type queries.
func (r *queryResolver) WorkView(ctx context.Context) (*graphql1.WorkView, error) {
	q := r.Resolver.Query()

	repos, reposErr := q.Repos(ctx)
	sessions, sessionsErr := q.TmuxSessions(ctx, nil)
	instances, instancesErr := q.ClaudeInstances(ctx)

	view := &graphql1.WorkView{
		Repos:           repos,
		TmuxSessions:    sessions,
		ClaudeInstances: instances,
		Meta: &graphql1.Meta{
			Provider:              metaProviderWorkView,
			LastSuccessfulFetchAt: nowRFC3339(),
		},
	}

	// Fold non-fatal sub-errors into the Meta envelope so callers can
	// distinguish "valid empty" from "data unavailable" (#469 F1)
	// without the whole composite failing.
	reasons := make([]string, 0, 3)
	if reposErr != nil {
		reasons = append(reasons, "repos: "+reposErr.Error())
	}
	if sessionsErr != nil {
		reasons = append(reasons, "tmuxSessions: "+sessionsErr.Error())
	}
	if instancesErr != nil {
		reasons = append(reasons, "claudeInstances: "+instancesErr.Error())
	}
	if len(reasons) > 0 {
		joined := strings.Join(reasons, "; ")
		view.Meta.FailureReason = &joined
		view.Meta.LastSuccessfulFetchAt = nil
	}

	if view.Repos == nil {
		view.Repos = []*graphql1.Repo{}
	}
	if view.TmuxSessions == nil {
		view.TmuxSessions = []*graphql1.TmuxSession{}
	}
	if view.ClaudeInstances == nil {
		view.ClaudeInstances = []*graphql1.ClaudeInstance{}
	}

	return view, nil
}

// DaemonState is the resolver for Query.daemonState (#469 F9). Reports per-provider configuration plus daemon-wide startedAt/uptime. Per-provider counters (refreshCount/failureCount) are reserved for follow-up wiring; v1 returns 0/nil best-effort.
func (r *queryResolver) DaemonState(ctx context.Context) (*graphql1.DaemonState, error) {
	startedAt := r.StartedAt.UTC().Format(time.RFC3339)
	uptime := int64(time.Since(r.StartedAt).Round(time.Second).Seconds())

	providers := []*graphql1.ProviderHealth{
		{Name: "host", Configured: r.HostProvider != nil},
		{Name: "git", Configured: r.Git != nil},
		{Name: "ps", Configured: r.PS != nil},
		{Name: "tmux", Configured: r.Tmux != nil},
		{Name: "claudeProjects", Configured: r.ClaudeProjects != nil},
		{Name: "claudeAccount", Configured: r.ClaudeAccount != nil},
		{Name: "claudeInstance", Configured: r.Tmux != nil},
		{Name: "hostService", Configured: r.HostServiceProvider != nil},
		{Name: "gh", Configured: r.GH != nil},
		{Name: "peerProxy", Configured: r.PeerProxy != nil},
	}

	return &graphql1.DaemonState{
		StartedAt: startedAt,
		UptimeS:   uptime,
		Providers: providers,
	}, nil
}

// Version is the resolver for Query.version (#417 AC2). Returns the daemon
// binary version baked in via -ldflags at release time, or "dev" when
// built without ldflags (plain `go build`). The value originates from the
// package-level `version` variable in cmd/orchard-daemon/main.go, injected
// into the resolver at boot via Resolver.WithVersion.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return r.DaemonVersion, nil
}

// Worktrees is the resolver for the repo.worktrees field.
func (r *repoResolver) Worktrees(ctx context.Context, obj *graphql1.Repo) ([]*graphql1.Worktree, error) {
	if r.Git == nil {
		return nil, fmt.Errorf("git provider not configured")
	}
	worktrees, err := r.Git.ListByProject(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("list worktrees for repo %q: %w", obj.ID, err)
	}
	out := make([]*graphql1.Worktree, 0, len(worktrees))
	for _, w := range worktrees {
		out = append(out, toGraphQLWorktree(w))
	}
	return out, nil
}

// NodeChanged is the resolver for the nodeChanged field.
func (r *subscriptionResolver) NodeChanged(ctx context.Context, id string) (<-chan graphql1.Node, error) {
	return subscribeNodeChanged(ctx, r.Resolver, id)
}

// Processes is the resolver for the processes field.
func (r *subscriptionResolver) Processes(ctx context.Context) (<-chan []*graphql1.Process, error) {
	return subscribeProcesses(ctx, r.Resolver)
}

// Peer is the resolver for the peer field.
func (r *subscriptionResolver) Peer(ctx context.Context, host string) (<-chan graphql1.Node, error) {
	if host == "*" {
		return r.streamLocalEvents(ctx)
	}
	if r.PeerProxy == nil {
		return nil, fmt.Errorf("peerproxy provider not wired")
	}
	stream, err := r.PeerProxy.SubscribePeer(ctx, host)
	if err != nil {
		return nil, err
	}
	out := make(chan graphql1.Node, 16)
	go func() {
		defer close(out)
		for ev := range stream {
			if ev.NodeID == "" {
				continue
			}
			node, err := r.PeerProxy.Get(ctx, ev.NodeID)
			if err != nil || node == nil {
				continue
			}
			projected, err := projectPeerNode(node)
			if err != nil {
				continue
			}
			select {
			case out <- projected:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// TmuxSessionsChanged is the resolver for Subscription.tmuxSessionsChanged (#469 F7). Emits a fresh snapshot of cached tmux sessions whenever the tmux provider invalidates.
func (r *subscriptionResolver) TmuxSessionsChanged(ctx context.Context) (<-chan []*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return nil, fmt.Errorf("tmux provider not configured")
	}
	src := r.Tmux.Sessions().Subscribe(ctx)
	out := make(chan []*graphql1.TmuxSession, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-src:
				if !ok {
					return
				}
				snap := r.Tmux.Snapshot()
				sessions := make([]*graphql1.TmuxSession, 0, len(snap.Sessions))
				for _, s := range snap.Sessions {
					sessions = append(sessions, projectSession(s))
				}
				select {
				case out <- sessions:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// PullRequestChanged is the resolver for Subscription.pullRequestChanged (#469 F7). Emits the freshly-loaded PullRequest each time the gh provider invalidates an id matching repo+number.
func (r *subscriptionResolver) PullRequestChanged(ctx context.Context, repo string, number int64) (<-chan *graphql1.PullRequest, error) {
	if r.GH == nil {
		return nil, errGHNotConfigured
	}
	if _, _, ok := splitRepo(repo); !ok {
		return nil, fmt.Errorf("pullRequestChanged: malformed repo %q (want owner/name)", repo)
	}
	// gh provider keys PullRequest events as `PullRequest:<owner>/<repo>#<number>`.
	wantKey := fmt.Sprintf("PullRequest:%s#%d", repo, number)
	src := r.GH.Subscribe(ctx)
	out := make(chan *graphql1.PullRequest, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-src:
				if !ok {
					return
				}
				if ev.Key != wantKey {
					continue
				}
				pr, err := r.Resolver.Query().PullRequest(ctx, repo, number)
				if err != nil || pr == nil {
					continue
				}
				select {
				case out <- pr:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// RunChanged is the resolver for Subscription.runChanged (#469 F7). Emits matching WorkflowRun snapshots when the gh provider invalidates.
func (r *subscriptionResolver) RunChanged(ctx context.Context, repo string, branch string) (<-chan *graphql1.WorkflowRun, error) {
	if r.GH == nil {
		return nil, errGHNotConfigured
	}
	if _, _, ok := splitRepo(repo); !ok {
		return nil, fmt.Errorf("runChanged: malformed repo %q (want owner/name)", repo)
	}
	src := r.GH.Subscribe(ctx)
	out := make(chan *graphql1.WorkflowRun, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-src:
				if !ok {
					return
				}
				if !strings.HasPrefix(ev.Key, "WorkflowRun:"+repo+"#") {
					continue
				}
				runs, err := r.Resolver.Query().WorkflowRuns(ctx, repo)
				if err != nil {
					continue
				}
				for _, run := range runs {
					if run == nil || run.HeadBranch != branch {
						continue
					}
					if ev.Key != fmt.Sprintf("WorkflowRun:%s#%d", repo, run.RunID) {
						continue
					}
					select {
					case out <- run:
					case <-ctx.Done():
						return
					}
					break
				}
			}
		}
	}()
	return out, nil
}

// WorktreeChanged is the resolver for Subscription.worktreeChanged (#469 F7). Emits the repo's full worktree list whenever the git provider invalidates any worktree belonging to the named repo.
func (r *subscriptionResolver) WorktreeChanged(ctx context.Context, repo string) (<-chan []*graphql1.Worktree, error) {
	if r.Git == nil {
		return nil, fmt.Errorf("git provider not configured")
	}
	src := r.Git.Subscribe(ctx)
	out := make(chan []*graphql1.Worktree, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-src:
				if !ok {
					return
				}
				if !worktreeEventMatchesProject(ev, repo) {
					continue
				}
				worktrees, err := r.Git.ListByProject(ctx, repo)
				if err != nil {
					continue
				}
				out2 := make([]*graphql1.Worktree, 0, len(worktrees))
				for _, w := range worktrees {
					out2 = append(out2, toGraphQLWorktree(w))
				}
				select {
				case out <- out2:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// ConversationChanged is the resolver for Subscription.conversationChanged (#525). Filters claudeprojects invalidations by sessionUUID and emits the freshly-loaded Conversation on each match. Emits nil when the fsnotify watcher reports the file was removed so callers can clear stale state.
func (r *subscriptionResolver) ConversationChanged(ctx context.Context, sessionUUID string) (<-chan *graphql1.Conversation, error) {
	if r.ClaudeProjects == nil {
		return nil, fmt.Errorf("claudeprojects provider not configured")
	}
	gqlid := "Conversation:" + sessionUUID
	src := r.ClaudeProjects.Subscribe(ctx)
	out := make(chan *graphql1.Conversation, 1)
	go func() {
		defer close(out)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-src:
				if !ok {
					return
				}
				if ev.Key.SessionUUID != sessionUUID {
					continue
				}
				if ev.Reason == "watcher-remove" {
					select {
					case out <- nil:
					case <-ctx.Done():
						return
					}
					continue
				}
				conv, err := r.Resolver.Query().Conversation(ctx, gqlid)
				if err != nil || conv == nil {
					continue
				}
				select {
				case out <- conv:
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return out, nil
}

// Server is the resolver for tmuxClient.server.
func (r *tmuxClientResolver) Server(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxServer, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	return projectServer(r.Tmux.Host(), r.Tmux.Server()), nil
}

// Session is the resolver for tmuxClient.session.
func (r *tmuxClientResolver) Session(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return &graphql1.TmuxSession{ID: "TmuxSession:"}, nil
	}
	c, ok := r.lookupClient(obj.ID)
	if !ok {
		return nil, nil
	}
	host := r.Tmux.Host()
	s, ok := r.Tmux.Snapshot().Sessions[tmux.SessionKey{Host: host, Name: c.Session}]
	if !ok {
		return nil, nil
	}
	return projectSession(s), nil
}

// Tty is the resolver for tmuxClient.tty.
func (r *tmuxClientResolver) Tty(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok {
		return "", nil
	}
	return c.TTY, nil
}

// Hostname is the resolver for tmuxClient.hostname.
func (r *tmuxClientResolver) Hostname(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok {
		return "", nil
	}
	return c.Hostname, nil
}

// TermName is the resolver for tmuxClient.termName.
func (r *tmuxClientResolver) TermName(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok {
		return "", nil
	}
	return c.TermName, nil
}

// AttachedAt is the resolver for tmuxClient.attachedAt.
func (r *tmuxClientResolver) AttachedAt(ctx context.Context, obj *graphql1.TmuxClient) (string, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok || c.AttachedAt.IsZero() {
		return "", nil
	}
	return c.AttachedAt.Format(time.RFC3339), nil
}

// LastActivityAt is the resolver for tmuxClient.lastActivityAt.
func (r *tmuxClientResolver) LastActivityAt(ctx context.Context, obj *graphql1.TmuxClient) (*string, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok || c.LastActivityAt.IsZero() {
		return nil, nil
	}
	v := c.LastActivityAt.Format(time.RFC3339)
	return &v, nil
}

// Readonly is the resolver for tmuxClient.readonly.
func (r *tmuxClientResolver) Readonly(ctx context.Context, obj *graphql1.TmuxClient) (bool, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok {
		return false, nil
	}
	return c.Readonly, nil
}

// CurrentWindow is the resolver for tmuxClient.currentWindow.
func (r *tmuxClientResolver) CurrentWindow(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxWindow, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok || r.Tmux == nil {
		return nil, nil
	}
	host := r.Tmux.Host()
	w, ok := r.Tmux.Snapshot().Windows[tmux.WindowKey{Host: host, Session: c.Session, Index: c.CurrentWindow}]
	if !ok {
		return nil, nil
	}
	return projectWindow(w), nil
}

// CurrentPane is the resolver for tmuxClient.currentPane.
func (r *tmuxClientResolver) CurrentPane(ctx context.Context, obj *graphql1.TmuxClient) (*graphql1.TmuxPane, error) {
	c, ok := r.lookupClient(obj.ID)
	if !ok || r.Tmux == nil || c.CurrentPane == "" {
		return nil, nil
	}
	host := r.Tmux.Host()
	p, ok := r.Tmux.Snapshot().Panes[tmux.PaneKey{Host: host, PaneID: c.CurrentPane}]
	if !ok {
		return nil, nil
	}
	return projectPane(p), nil
}

// Window is the resolver for tmuxPane.window.
func (r *tmuxPaneResolver) Window(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.TmuxWindow, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok || r.Tmux == nil {
		return nil, nil
	}
	host := r.Tmux.Host()
	w, ok := r.Tmux.Snapshot().Windows[tmux.WindowKey{Host: host, Session: p.WindowKey.Session, Index: p.WindowKey.Index}]
	if !ok {
		return nil, nil
	}
	return projectWindow(w), nil
}

// Title is the resolver for tmuxPane.title.
func (r *tmuxPaneResolver) Title(ctx context.Context, obj *graphql1.TmuxPane) (string, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return "", nil
	}
	return p.Title, nil
}

// CurrentCommand is the resolver for tmuxPane.currentCommand.
func (r *tmuxPaneResolver) CurrentCommand(ctx context.Context, obj *graphql1.TmuxPane) (string, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return "", nil
	}
	return p.CurrentCommand, nil
}

// CurrentPid is the resolver for tmuxPane.currentPid.
func (r *tmuxPaneResolver) CurrentPid(ctx context.Context, obj *graphql1.TmuxPane) (*int64, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok || p.CurrentPid == 0 {
		return nil, nil
	}
	v := int64(p.CurrentPid)
	return &v, nil
}

// Width is the resolver for tmuxPane.width.
func (r *tmuxPaneResolver) Width(ctx context.Context, obj *graphql1.TmuxPane) (int64, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return 0, nil
	}
	return int64(p.Width), nil
}

// Height is the resolver for tmuxPane.height.
func (r *tmuxPaneResolver) Height(ctx context.Context, obj *graphql1.TmuxPane) (int64, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return 0, nil
	}
	return int64(p.Height), nil
}

// Dead is the resolver for tmuxPane.dead.
func (r *tmuxPaneResolver) Dead(ctx context.Context, obj *graphql1.TmuxPane) (bool, error) {
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return false, nil
	}
	return p.Dead, nil
}

// WatchingClients is the resolver for tmuxPane.watchingClients.
func (r *tmuxPaneResolver) WatchingClients(ctx context.Context, obj *graphql1.TmuxPane) ([]*graphql1.TmuxClient, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return nil, nil
	}
	out := []*graphql1.TmuxClient{}
	for _, c := range r.Tmux.Snapshot().Clients {
		if c.CurrentPane == p.Key.PaneID {
			out = append(out, projectClient(c))
		}
	}
	return out, nil
}

// Process returns the OS-level Process for the pane's foreground pid (nil when the pid is missing or absent from the cached ps snapshot). cwd resolution is delegated to processResolver.Cwd and fires only when the client selects cwd. Host segment of the pane id is preserved on the projected Process node so future federated lookup attributes it to the correct peer host; today lookupPane only resolves local-tmux panes.
func (r *tmuxPaneResolver) Process(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.Process, error) {
	if r.PS == nil {
		return nil, nil
	}
	pane, ok := r.lookupPane(obj.ID)
	if !ok || pane.CurrentPid == 0 {
		return nil, nil
	}
	host, _, ok := splitTmuxPaneID(obj.ID)
	if !ok {
		return nil, nil
	}
	target := ps.ProcessID{Host: host, PID: pane.CurrentPid}
	got, _, err := r.PS.GetMany(ctx, []ps.ProcessID{target})
	if err != nil {
		return nil, nil
	}
	proc, ok := got[target]
	if !ok {
		return nil, nil
	}
	return projectProcess(&proc, host), nil
}

// ClaudeInstance resolves the ClaudeInstance running inside this pane.
// Pane-first path (ADR-022 Phase 5): builds the instance directly from the
// pane when the pane's command is "claude". Returns nil when Tmux is not
// wired or the pane is not a claude pane.
func (r *tmuxPaneResolver) ClaudeInstance(ctx context.Context, obj *graphql1.TmuxPane) (*graphql1.ClaudeInstance, error) {
	if r.Tmux == nil || obj == nil {
		return nil, nil
	}
	// obj is a thin handle: tmuxWindowResolver.Panes projects panes through
	// projectPane(), which sets {ID, PaneID} and nothing else. Every sibling
	// field resolver (currentCommand, currentPid, process) therefore looks the
	// pane up in the provider rather than reading obj. This one used to read
	// obj.CurrentCommand, which compared "" against "claude" and so returned
	// nil for EVERY pane, always — attend.js reads this field and treats null
	// as healthy, leaving the attention feed blind to every worker (#706).
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return nil, nil
	}
	host := string(r.Tmux.Host())
	// Only project panes running claude — same two-signal detection as
	// Query.claudeInstances, so both surfaces agree on what "running claude" means.
	if !tmux.PaneRunsCommand(p, host, newResolverPanePsGetter(r.PS), "claude") {
		return nil, nil
	}
	qr := &queryResolver{r.Resolver}
	// nil procTree: the single-pane path builds a one-off tree internally (#711).
	inst := qr.buildClaudeInstanceFromPane(ctx, projectPaneRich(p), host, nil, nil, nil, nil)
	return inst, nil
}

// Content is the resolver for tmuxPane.content.
func (r *tmuxPaneResolver) Content(ctx context.Context, obj *graphql1.TmuxPane, lines *int64, stripAnsi *bool) (string, error) {
	if r.Tmux == nil {
		return "", fmt.Errorf("tmux provider not wired")
	}
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return "", fmt.Errorf("pane %q not found", obj.ID)
	}
	n := 50
	if lines != nil {
		n = int(*lines)
	}
	strip := true
	if stripAnsi != nil {
		strip = *stripAnsi
	}
	return r.Tmux.CapturePaneTail(ctx, p.Key, n, strip)
}

// ContentRange is the resolver for tmuxPane.contentRange.
func (r *tmuxPaneResolver) ContentRange(ctx context.Context, obj *graphql1.TmuxPane, startLine int64, endLine int64, stripAnsi *bool) (string, error) {
	if r.Tmux == nil {
		return "", fmt.Errorf("tmux provider not wired")
	}
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return "", fmt.Errorf("pane %q not found", obj.ID)
	}
	strip := true
	if stripAnsi != nil {
		strip = *stripAnsi
	}
	return r.Tmux.CapturePane(ctx, p.Key, int(startLine), int(endLine), false, strip)
}

// ContentFull is the resolver for tmuxPane.contentFull.
func (r *tmuxPaneResolver) ContentFull(ctx context.Context, obj *graphql1.TmuxPane, stripAnsi *bool) (string, error) {
	if r.Tmux == nil {
		return "", fmt.Errorf("tmux provider not wired")
	}
	p, ok := r.lookupPane(obj.ID)
	if !ok {
		return "", fmt.Errorf("pane %q not found", obj.ID)
	}
	strip := true
	if stripAnsi != nil {
		strip = *stripAnsi
	}
	return r.Tmux.CapturePane(ctx, p.Key, 0, 0, true, strip)
}

// Pid is the resolver for tmuxServer.pid.
func (r *tmuxServerResolver) Pid(ctx context.Context, obj *graphql1.TmuxServer) (*int64, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	if pid := r.Tmux.Server().Pid; pid != 0 {
		v := int64(pid)
		return &v, nil
	}
	return nil, nil
}

// Alive is the resolver for tmuxServer.alive.
func (r *tmuxServerResolver) Alive(ctx context.Context, obj *graphql1.TmuxServer) (bool, error) {
	if r.Tmux == nil {
		return false, nil
	}
	return r.Tmux.Server().Alive, nil
}

// Sessions is the resolver for tmuxServer.sessions. Sort key defaults to LAST_ACTIVITY (most-recently-active first; lex name break ties; sessions with zero activity rank below those with one).
func (r *tmuxServerResolver) Sessions(ctx context.Context, obj *graphql1.TmuxServer, sort *graphql1.TmuxSessionSort) ([]*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	snap := r.Tmux.Snapshot()
	sessions := make([]tmux.Session, 0, len(snap.Sessions))
	for _, s := range snap.Sessions {
		sessions = append(sessions, s)
	}

	key := graphql1.TmuxSessionSortLastActivity
	if sort != nil {
		key = *sort
	}
	switch key {
	case graphql1.TmuxSessionSortName:
		slices.SortStableFunc(sessions, func(a, b tmux.Session) int {
			if a.Key.Name < b.Key.Name {
				return -1
			}
			if a.Key.Name > b.Key.Name {
				return 1
			}
			return 0
		})
	default: // LAST_ACTIVITY
		slices.SortStableFunc(sessions, func(a, b tmux.Session) int {
			aZero := a.LastActivityAt.IsZero()
			bZero := b.LastActivityAt.IsZero()
			if aZero != bZero {
				if !aZero {
					return -1
				}
				return 1
			}
			if !a.LastActivityAt.Equal(b.LastActivityAt) {
				if a.LastActivityAt.After(b.LastActivityAt) {
					return -1
				}
				return 1
			}
			if a.Key.Name < b.Key.Name {
				return -1
			}
			if a.Key.Name > b.Key.Name {
				return 1
			}
			return 0
		})
	}

	out := make([]*graphql1.TmuxSession, 0, len(sessions))
	for _, s := range sessions {
		out = append(out, projectSession(s))
	}
	return out, nil
}

// Clients is the resolver for tmuxServer.clients.
func (r *tmuxServerResolver) Clients(ctx context.Context, obj *graphql1.TmuxServer) ([]*graphql1.TmuxClient, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	snap := r.Tmux.Snapshot()
	out := make([]*graphql1.TmuxClient, 0, len(snap.Clients))
	for _, c := range snap.Clients {
		out = append(out, projectClient(c))
	}
	return out, nil
}

// Server is the resolver for tmuxSession.server.
func (r *tmuxSessionResolver) Server(ctx context.Context, obj *graphql1.TmuxSession) (*graphql1.TmuxServer, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	return projectServer(r.Tmux.Host(), r.Tmux.Server()), nil
}

// CreatedAt is the resolver for tmuxSession.createdAt.
func (r *tmuxSessionResolver) CreatedAt(ctx context.Context, obj *graphql1.TmuxSession) (string, error) {
	s, ok := r.lookupSession(obj.ID)
	if !ok || s.CreatedAt.IsZero() {
		return "", nil
	}
	return s.CreatedAt.Format(time.RFC3339), nil
}

// Attached is the resolver for tmuxSession.attached.
func (r *tmuxSessionResolver) Attached(ctx context.Context, obj *graphql1.TmuxSession) (bool, error) {
	s, ok := r.lookupSession(obj.ID)
	if !ok {
		return false, nil
	}
	return s.Attached, nil
}

// ActiveAttached is the resolver for tmuxSession.activeAttached.
func (r *tmuxSessionResolver) ActiveAttached(ctx context.Context, obj *graphql1.TmuxSession) (bool, error) {
	s, ok := r.lookupSession(obj.ID)
	if !ok || !s.Attached {
		return false, nil
	}
	return true, nil
}

// AttachedClients is the resolver for tmuxSession.attachedClients.
func (r *tmuxSessionResolver) AttachedClients(ctx context.Context, obj *graphql1.TmuxSession) ([]*graphql1.TmuxClient, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	s, ok := r.lookupSession(obj.ID)
	if !ok {
		return nil, nil
	}
	out := []*graphql1.TmuxClient{}
	for _, c := range r.Tmux.Snapshot().Clients {
		if c.Session == s.Key.Name {
			out = append(out, projectClient(c))
		}
	}
	return out, nil
}

// LastActivityAt is the resolver for tmuxSession.lastActivityAt.
func (r *tmuxSessionResolver) LastActivityAt(ctx context.Context, obj *graphql1.TmuxSession) (*string, error) {
	s, ok := r.lookupSession(obj.ID)
	if !ok || s.LastActivityAt.IsZero() {
		return nil, nil
	}
	v := s.LastActivityAt.Format(time.RFC3339)
	return &v, nil
}

// Windows is the resolver for tmuxSession.windows.
func (r *tmuxSessionResolver) Windows(ctx context.Context, obj *graphql1.TmuxSession) ([]*graphql1.TmuxWindow, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	s, ok := r.lookupSession(obj.ID)
	if !ok {
		return nil, nil
	}
	out := []*graphql1.TmuxWindow{}
	for _, w := range r.Tmux.Snapshot().Windows {
		if w.Key.Session == s.Key.Name {
			out = append(out, projectWindow(w))
		}
	}
	return out, nil
}

// CurrentWindow is the resolver for tmuxSession.currentWindow.
func (r *tmuxSessionResolver) CurrentWindow(ctx context.Context, obj *graphql1.TmuxSession) (*graphql1.TmuxWindow, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	s, ok := r.lookupSession(obj.ID)
	if !ok {
		return nil, nil
	}
	host := r.Tmux.Host()
	w, ok := r.Tmux.Snapshot().Windows[tmux.WindowKey{Host: host, Session: s.Key.Name, Index: s.CurrentWindow}]
	if !ok {
		return nil, nil
	}
	return projectWindow(w), nil
}

// Session is the resolver for tmuxWindow.session.
func (r *tmuxWindowResolver) Session(ctx context.Context, obj *graphql1.TmuxWindow) (*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	w, ok := r.lookupWindow(obj.ID)
	if !ok {
		return nil, nil
	}
	host := r.Tmux.Host()
	s, ok := r.Tmux.Snapshot().Sessions[tmux.SessionKey{Host: host, Name: w.Key.Session}]
	if !ok {
		return nil, nil
	}
	return projectSession(s), nil
}

// Name is the resolver for tmuxWindow.name.
func (r *tmuxWindowResolver) Name(ctx context.Context, obj *graphql1.TmuxWindow) (string, error) {
	w, ok := r.lookupWindow(obj.ID)
	if !ok {
		return "", nil
	}
	return w.Name, nil
}

// Active is the resolver for tmuxWindow.active.
func (r *tmuxWindowResolver) Active(ctx context.Context, obj *graphql1.TmuxWindow) (bool, error) {
	w, ok := r.lookupWindow(obj.ID)
	if !ok {
		return false, nil
	}
	return w.Active, nil
}

// Panes is the resolver for tmuxWindow.panes.
func (r *tmuxWindowResolver) Panes(ctx context.Context, obj *graphql1.TmuxWindow) ([]*graphql1.TmuxPane, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	w, ok := r.lookupWindow(obj.ID)
	if !ok {
		return nil, nil
	}
	out := []*graphql1.TmuxPane{}
	for _, p := range r.Tmux.Snapshot().Panes {
		if p.WindowKey.Session == w.Key.Session && p.WindowKey.Index == w.Key.Index {
			out = append(out, projectPane(p))
		}
	}
	return out, nil
}

// CurrentPane is the resolver for tmuxWindow.currentPane.
func (r *tmuxWindowResolver) CurrentPane(ctx context.Context, obj *graphql1.TmuxWindow) (*graphql1.TmuxPane, error) {
	if r.Tmux == nil {
		return nil, nil
	}
	w, ok := r.lookupWindow(obj.ID)
	if !ok || w.CurrentPane == "" {
		return nil, nil
	}
	host := r.Tmux.Host()
	p, ok := r.Tmux.Snapshot().Panes[tmux.PaneKey{Host: host, PaneID: w.CurrentPane}]
	if !ok {
		return nil, nil
	}
	return projectPane(p), nil
}

// Host is the resolver for the worktree.host field. Reads obj.Host (set by toGraphQLWorktree); defensively falls back to "local" when empty so the v1 sentinel lives in one place.
func (r *worktreeResolver) Host(ctx context.Context, obj *graphql1.Worktree) (string, error) {
	if obj.Host == "" {
		return "local", nil
	}
	return obj.Host, nil
}

// Repo is the resolver for the worktree.repo field. Derives owner/repo from the worktree's origin remote URL; returns nil when origin is absent or not a GitHub URL.
func (r *worktreeResolver) Repo(ctx context.Context, obj *graphql1.Worktree) (*string, error) {
	if obj == nil || obj.Path == "" {
		return nil, nil
	}
	url, err := gh.ReadOriginURL(obj.Path)
	if err != nil {
		return nil, nil
	}
	owner, name, ok := gh.ParseGitHubURL(url)
	if !ok {
		return nil, nil
	}
	slug := owner + "/" + name
	return &slug, nil
}

// Pr is the resolver for the worktree.pr field. Looks up a PR whose headRef matches the worktree's branch via the PullRequestsForRepo DataLoader (which fetches PRs in all states per issue #489 so the TUI stale-fade UX works post-merge). Selection precedence: an OPEN match wins; otherwise the most-recent CLOSED/MERGED match. Returns nil for missing obj, empty branch, default branch, non-GitHub origin, or no headRef match in any state.
func (r *worktreeResolver) Pr(ctx context.Context, obj *graphql1.Worktree) (*graphql1.PullRequest, error) {
	if obj == nil || obj.Branch == "" {
		return nil, nil
	}
	// Default-branch exclusion: the default branch never has its own PR
	// targeting itself, so skip the DataLoader call entirely.
	if defaultBranch, ok := readDefaultBranch(obj.Path); ok && defaultBranch == obj.Branch {
		return nil, nil
	}
	// Derive the repo slug from the worktree's origin remote.
	url, err := gh.ReadOriginURL(obj.Path)
	if err != nil {
		return nil, nil // missing origin → null (graceful)
	}
	owner, name, ok := gh.ParseGitHubURL(url)
	if !ok {
		return nil, nil // non-GitHub origin → null
	}
	// Load all PRs (across all states) for the repo via the DataLoader.
	ldrs := loaders.FromContext(ctx)
	if ldrs == nil {
		return nil, fmt.Errorf("loaders not in context")
	}
	prs, err := ldrs.PullRequestsForRepo.Load(ctx, loaders.RepoKey{Owner: owner, Name: name})()
	if err != nil {
		return nil, err
	}
	// First pass: prefer any OPEN PR — the list is already sorted UpdatedAt
	// DESC by the GitHub API, so the first match is most-recent. Track the
	// first non-OPEN match as a fallback for the post-merge stale-fade case.
	var fallback *graphql1.PullRequest
	for _, pr := range prs {
		if pr == nil || pr.HeadRef != obj.Branch {
			continue
		}
		if pr.State == graphql1.PullRequestStateOpen {
			return pr, nil
		}
		if fallback == nil {
			fallback = pr
		}
	}
	return fallback, nil
}

// Issue is the resolver for the worktree.issue field. Parses the issue number from the worktree branch (rules ported from crates/orchard/src/github.rs) then fetches via the gh provider. Returns nil for empty branch, unparseable branch, missing/non-GitHub origin, unwired gh provider, or 404.
func (r *worktreeResolver) Issue(ctx context.Context, obj *graphql1.Worktree) (*graphql1.Issue, error) {
	if obj == nil || obj.Branch == "" {
		return nil, nil
	}

	n, ok := gh.ExtractIssueNumber(obj.Branch)
	if !ok {
		return nil, nil
	}

	url, err := gh.ReadOriginURL(obj.Path)
	if err != nil {
		return nil, nil
	}
	owner, name, ok := gh.ParseGitHubURL(url)
	if !ok {
		return nil, nil
	}

	if r.GH == nil {
		return nil, errGHNotConfigured
	}

	issue, err := r.GH.GetIssue(ctx, gh.IssueKey{Owner: owner, Name: name, Number: n})
	if err != nil {
		if gh.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return toGraphQLIssue(issue), nil
}

// Processes is the resolver for the worktree.processes field.
func (r *worktreeResolver) Processes(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.Process, error) {
	return []*graphql1.Process{}, nil
}

// TmuxPanes resolves Worktree.tmuxPanes (#511): returns every tmux pane on the worktree's host whose foreground-process cwd equals obj.Path exactly OR has obj.Path+"/" as a prefix. Panes are sorted by paneId ascending (lex sort: "%2" < "%5" < "%9"). Returns [] (never nil) when no panes match or when the tmux or ps provider is unwired.
func (r *worktreeResolver) TmuxPanes(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.TmuxPane, error) {
	if r.Tmux == nil {
		return []*graphql1.TmuxPane{}, nil
	}

	snap := r.Tmux.Snapshot()
	rawPanes := matchPanesForWorktree(ctx, r, snap, obj)

	// Map raw provider panes to GraphQL projection.
	out := make([]*graphql1.TmuxPane, len(rawPanes))
	for i, p := range rawPanes {
		out[i] = projectPane(p)
	}

	// Sort by paneId ascending so output is deterministic.
	sort.Slice(out, func(i, j int) bool {
		return out[i].PaneID < out[j].PaneID
	})

	return out, nil
}

// TmuxSession resolves Worktree.tmuxSession (#511): returns the most-recently-active TmuxSession among the matching panes; ties on lastActivityAt break to the lexicographically-first name. Returns nil when tmuxPanes is empty.
func (r *worktreeResolver) TmuxSession(ctx context.Context, obj *graphql1.Worktree) (*graphql1.TmuxSession, error) {
	if r.Tmux == nil {
		return nil, nil
	}

	snap := r.Tmux.Snapshot()
	matching := matchPanesForWorktree(ctx, r, snap, obj)
	if len(matching) == 0 {
		return nil, nil
	}

	// Collect the unique sessions that the matching panes belong to.
	// Raw panes carry WindowKey.Session directly — no need to re-key
	// into snap.Panes, eliminating snapshot-drift and silent-drop risk.
	seen := make(map[tmux.SessionKey]tmux.Session)
	for _, pane := range matching {
		sessionKey := tmux.SessionKey{Host: pane.Key.Host, Name: pane.WindowKey.Session}
		if _, already := seen[sessionKey]; already {
			continue
		}
		// Look up the Session to get its LastActivityAt.
		s, ok := snap.Sessions[sessionKey]
		if !ok {
			// Snapshot inconsistency: pane references a session that is absent
			// from snap.Sessions. Skip rather than synthesise a zero-activity
			// placeholder — the missing session is not a valid candidate.
			continue
		}
		seen[sessionKey] = s
	}

	if len(seen) == 0 {
		return nil, nil
	}

	// Flatten and sort: most-recently-active first; lex-lower name breaks ties.
	sessions := make([]tmux.Session, 0, len(seen))
	for _, s := range seen {
		sessions = append(sessions, s)
	}
	sort.Slice(sessions, func(i, j int) bool {
		a, b := sessions[i], sessions[j]
		// Zero LastActivityAt is treated as the lowest possible time, so
		// sessions with a real activity time always rank before those without.
		aZero := a.LastActivityAt.IsZero()
		bZero := b.LastActivityAt.IsZero()
		if aZero != bZero {
			// whichever has a real time goes first (i is "less" in sort order
			// = appears earlier = "wins").
			return !aZero // a has real time, b does not → a wins
		}
		if !a.LastActivityAt.Equal(b.LastActivityAt) {
			return a.LastActivityAt.After(b.LastActivityAt) // later = higher priority
		}
		// Deterministic tie-break: lex-lower name wins.
		return a.Key.Name < b.Key.Name
	})

	return projectSession(sessions[0]), nil
}

// ClaudeInstances resolves Worktree.claudeInstances (#540): every
// ClaudeInstance whose resolved process cwd lies under obj.Path.
// Returns []*graphql1.ClaudeInstance{} (never nil) when no match.
// See worktree_claude.go for the matching logic; mirrors
// Worktree.tmuxPanes (worktree_tmux.go) in shape and locking.
func (r *worktreeResolver) ClaudeInstances(ctx context.Context, obj *graphql1.Worktree) ([]*graphql1.ClaudeInstance, error) {
	if obj == nil {
		return []*graphql1.ClaudeInstance{}, nil
	}
	return matchClaudeInstancesForWorktree(ctx, r, obj)
}

// ClaudeInstance returns graphql1.ClaudeInstanceResolver implementation.
func (r *Resolver) ClaudeInstance() graphql1.ClaudeInstanceResolver {
	return &claudeInstanceResolver{r}
}

// Host returns graphql1.HostResolver implementation.
func (r *Resolver) Host() graphql1.HostResolver { return &hostResolver{r} }

// Issue returns graphql1.IssueResolver implementation.
func (r *Resolver) Issue() graphql1.IssueResolver { return &issueResolver{r} }

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Process returns graphql1.ProcessResolver implementation.
func (r *Resolver) Process() graphql1.ProcessResolver { return &processResolver{r} }

// PullRequest returns graphql1.PullRequestResolver implementation.
func (r *Resolver) PullRequest() graphql1.PullRequestResolver { return &pullRequestResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Repo returns graphql1.RepoResolver implementation.
func (r *Resolver) Repo() graphql1.RepoResolver { return &repoResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

// TmuxClient returns graphql1.TmuxClientResolver implementation.
func (r *Resolver) TmuxClient() graphql1.TmuxClientResolver { return &tmuxClientResolver{r} }

// TmuxPane returns graphql1.TmuxPaneResolver implementation.
func (r *Resolver) TmuxPane() graphql1.TmuxPaneResolver { return &tmuxPaneResolver{r} }

// TmuxServer returns graphql1.TmuxServerResolver implementation.
func (r *Resolver) TmuxServer() graphql1.TmuxServerResolver { return &tmuxServerResolver{r} }

// TmuxSession returns graphql1.TmuxSessionResolver implementation.
func (r *Resolver) TmuxSession() graphql1.TmuxSessionResolver { return &tmuxSessionResolver{r} }

// TmuxWindow returns graphql1.TmuxWindowResolver implementation.
func (r *Resolver) TmuxWindow() graphql1.TmuxWindowResolver { return &tmuxWindowResolver{r} }

// Worktree returns graphql1.WorktreeResolver implementation.
func (r *Resolver) Worktree() graphql1.WorktreeResolver { return &worktreeResolver{r} }

type claudeInstanceResolver struct{ *Resolver }
type hostResolver struct{ *Resolver }
type issueResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type processResolver struct{ *Resolver }
type pullRequestResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type repoResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tmuxClientResolver struct{ *Resolver }
type tmuxPaneResolver struct{ *Resolver }
type tmuxServerResolver struct{ *Resolver }
type tmuxSessionResolver struct{ *Resolver }
type tmuxWindowResolver struct{ *Resolver }
type worktreeResolver struct{ *Resolver }
